Activity_API_2
Yuanpei-Intelligence/YPPF pull request #127
Opened 2021-08-17 17:36 UTC by pkuGenuine

Add front_end check to activity page

Reconstructed backend codes

Add schduler job & notification ( partial )

Lots to do......

2021-08-17 20:23 UTC, YWolfeee requested changes
确实很多东西需要讨论，我们找时间电话一点一点说吧

2021-08-17 20:23 UTC, YWolfeee commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'])
如果你加了reminder但是这个活动取消了，这个reminder会取消吗？
另外你现在的微信发送测试过没有

2021-08-17 20:23 UTC, YWolfeee commented on app/scheduler_func.py
> +                    participant.save()
签到不是在这里做。签到的逻辑是默认全部签到，但是如果组织打开了签到二维码那么就是默认不签到。这个可以和杜逸恒去交流，他应该已经写了后者

2021-08-18 00:40 UTC, pkuGenuine commented on app/views.py
> +        context = utils.check_ac_request(request)
现在在调试没用 try，带 try 的写法注释掉了。如果保证前端的 check 没问题，welcome 如果是恶意的为啥要提醒呢？

2021-08-18 00:48 UTC, pkuGenuine commented on app/utils.py
> +    assert signup_start <= signup_end
前端进行了 check。后端的逻辑好像是有一点问题...... 
我觉得可以给一个是否重新开放报名的选项，如果选了，则要求报名截止时间晚于当前时间，否则可以直接改？

2021-08-18 00:48 UTC, pkuGenuine commented on app/views.py
> +                    notifyActivity(activity.id, 'participants')
我想想怎么整合

2021-08-18 00:49 UTC, pkuGenuine commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'])
目前的想法是活动状态变更的时候进行修改，包括时间变更，活动取消

2021-08-18 00:50 UTC, pkuGenuine commented on app/views.py
> +    a. 创建活动的界面，placeholder 为 prompt
感觉工作量还挺大的...... 之后再说吧 /facepalm

2021-08-18 00:52 UTC, pkuGenuine commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'])
微信还没测试，感觉这个算是辅助功能，可以放到最后一起调

2021-08-18 01:42 UTC, YWolfeee commented on app/utils.py
> +    assert signup_start <= signup_end
我觉得不是重新报名。是说已经截止了但是这时候我还能调整活动时间。但是我调整之后的时间可能就不满足signupstart<signupend，就导致我改不了时间

2021-08-18 01:42 UTC, YWolfeee commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'])
我建议你把所有的reminder统一一个地方添加&删除，不要给自己做这种一个注册下一个注册下一个的复杂逻辑

2021-08-22 11:00 UTC, XuRuihan commented on app/scheduler_func.py
> +        pass
别写成这样，至少写成
```suggestion
    except Exception as e:
        print(e)
```
这样还能在命令行里看到报错，不然测试的既不显示出错位置，也不显示出错类型，根本找不到问题

2021-08-22 11:04 UTC, pkuGenuine commented on templates/activity_add.html
> +    document.getElementById('datetimepicker4').placeholder='{{end}}';
是这个意思，这样在后端代码可以统一一些，不会太冗余

2021-08-22 11:04 UTC, pkuGenuine commented on app/activity_utils.py
> +    organization.save()
数据库 transaction 会自动处理死锁吧？

2021-08-22 11:05 UTC, pkuGenuine commented on app/wechat_send.py
> +        userids = targets[i:i+500]   # 一次最多接受1000个，方便传送只发500个
slice 可以超不会出异常

2021-08-22 11:05 UTC, pkuGenuine commented on app/scheduler_func.py
> +        pass
好的

2021-08-22 11:07 UTC, pkuGenuine commented on app/activity_utils.py
> +    assert len(context['location']) > 0
如果调用 activity_utils.py 里的函数，在外层都需要 try

2021-08-22 22:27 UTC, YWolfeee reviewed
确认一下现在抽签而不是投点，是不是已经实现了？

2021-08-22 22:27 UTC, YWolfeee commented on app/views.py
> +        '''
可以会有什么问题？

2021-08-22 22:27 UTC, YWolfeee commented on app/views.py
> +        if pStatus == "放弃":
这是什么意思呀？

2021-08-22 22:27 UTC, YWolfeee commented on app/views.py
> -                html_display["warn_message"] = "活动已进行 12 小时以上，不能取消。"
有一个问题，如果活动以结束再取消，其这个逻辑很奇怪，我建议就只能在活动开始前或者最多活动结束前取消吧，不然你活动已经变成已结束了，然后再取消这个时候这个逻辑可能有很多问题，我们没有考虑到，比如说如果经费已经申请了，怎么办？

2021-08-22 22:27 UTC, YWolfeee commented on app/views.py
> +                signscheme = "投点参与"
是不是现在改成先到先得和抽签，就把这个给去掉了？

2021-08-23 01:41 UTC, pkuGenuine commented on app/models.py
> +    last_time_login = models.DateTimeField("活动开始时间", blank=True, null=True)
抽签，投点都实现了，晚上统一改成抽签。

2021-08-23 01:43 UTC, pkuGenuine commented on app/models.py
> +    apply_end = models.DateTimeField("报名截止时间", blank=True, default=datetime.now)
因为允许组织选择是否调整报名时间。如果修改了 start 并且选择了不调整时间，则与 endbefore 不一致。这里其实 endbefore 是有点冗余的，而不是 apply_end

2021-08-23 01:44 UTC, pkuGenuine commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'], replace_existing=True)
那就不循环都加好，晚上改

2021-08-23 01:44 UTC, pkuGenuine commented on app/scheduler_func.py
> +
了解

2021-08-23 01:45 UTC, pkuGenuine commented on app/views.py
> +        '''
技术上没问题，业务上不知道？你觉得业务上有问题吗？

2021-08-23 01:45 UTC, pkuGenuine commented on app/views.py
> +        if pStatus == "放弃":
前端展示用的

2021-08-23 01:46 UTC, pkuGenuine commented on app/views.py
> -                html_display["warn_message"] = "活动已进行 12 小时以上，不能取消。"
OK， 加一个结束前的 check

2021-08-23 01:46 UTC, pkuGenuine commented on app/views.py
> +                signscheme = "投点参与"
其实相当于 bidding 就是抽签。没改名而已

2021-08-23 03:32 UTC, YWolfeee commented on app/models.py
> +    apply_end = models.DateTimeField("报名截止时间", blank=True, default=datetime.now)
但是并不希望组织填写那么多时间，也不希望在报名时间上提供那么多选项，因为这样发起活动的时候要填太多时间会很麻烦

2021-08-23 03:32 UTC, YWolfeee commented on app/views.py
> +        '''
我觉得少一个不允许总不是坏事，因为老师也不会专门搞事情

2021-08-23 03:33 UTC, YWolfeee commented on app/views.py
> +        if pStatus == "放弃":
前端展示量，要不放到`html_display`中，要不请加注释`# 用于前端展示+具体作用`

2021-08-23 03:33 UTC, YWolfeee commented on app/views.py
> -                html_display["warn_message"] = "活动已进行 12 小时以上，不能取消。"
啥意思 我的建议是只能在结束前取消（

2021-08-23 04:01 UTC, pkuGenuine commented on app/views.py
> -                html_display["warn_message"] = "活动已进行 12 小时以上，不能取消。"
嗯，懂你意思，就是说要 check 一下活动还没结束

2021-08-23 05:43 UTC, XuRuihan commented on app/scheduler_func.py
> +            participant.save()
`participants[:5].update(...)`

2021-08-23 16:23 UTC, pkuGenuine commented on app/models.py
> +    apply_end = models.DateTimeField("报名截止时间", blank=True, default=datetime.now)
即使调整时间，也是选择一小时前或者一天前这样，我觉得还好

2021-08-23 17:02 UTC, pkuGenuine commented on app/models.py
> +    last_time_login = models.DateTimeField("活动开始时间", blank=True, null=True)
这个改完了

2021-08-23 17:02 UTC, pkuGenuine commented on app/models.py
> +    quota = models.FloatField("配额", default=0)
这个改了

2021-08-23 17:06 UTC, pkuGenuine commented on app/scheduler_func.py
> +                    run_date=activity.act_start - timedelta(minutes=15), args=[activity.id, 'remind'], replace_existing=True)
改了

2021-08-23 17:36 UTC, pkuGenuine commented on app/scheduler_func.py
> +            participant.save()
没找到根据 index 更新的 API，而且估计也没有。这东西在 sql 里也没法实现

2021-08-23 17:36 UTC, pkuGenuine commented on app/views.py
> +        '''
那就保持是注释的情况

2021-08-23 17:38 UTC, pkuGenuine commented on app/views.py
> +        if pStatus == "放弃":
viewActivity 设计就是来展示页面的，里面一堆变量，没必要都放到 `html_display` 里。我在一开始加个总的注释

2021-08-23 17:46 UTC, pkuGenuine commented on app/views.py
> -                html_display["warn_message"] = "活动已进行 12 小时以上，不能取消。"
代码本来就不支持活动结束后取消。现在前端也不支持活动开始之后取消，但后端的接口有。我觉得就这样吧，因为活动开始后取消本来就是个补救措施

2021-08-23 17:46 UTC, pkuGenuine commented on app/views.py
> +                signscheme = "投点参与"
改变量名最后都放一起吧，挺多地方需要改变量名的

2021-08-24 01:44 UTC, merged