解决welcome页面如果没有活动图片出bug的问题
Yuanpei-Intelligence/YPPF pull request #198
Opened 2021-08-27 11:25 UTC by Sophie-zh

2021-08-27 23:44 UTC, YWolfeee requested changes
问题比较多，但是这个界面很重要，请在我的周五晚上之前搞定，我争取晚上merge掉；周末应该要上服务器了

2021-08-27 23:44 UTC, YWolfeee commented on app/models.py
> +    show_grade = models.BooleanField(default=True)
这种修改为什么还会存在？我合理怀疑你的merge有问题...

2021-08-27 23:44 UTC, YWolfeee commented on app/models.py
> +
同意，写法如下。
在`ActivityPhoto`这个类中增加字段`type = choices in [预告, 总结]`，然后related_name直接写`photos`。
想要根据一个活动调用某一类图片的之后，直接写`activity.photos.filter(type=...)`

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +    ModifyOrganization,
这个修改不是你进行的吧 要不你关了这个PR重新发一次？发之前pull latest develop

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +    )
同意，直接把这个丢到那个class里面，然后写一个什么`get_week_valid_activity`，或者把一周当成参数传进去写个什么`get_recent_activity(day = 7)`

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +    wishes = Wishes.objects.all()[:100]
如果心愿墙为空，你有做任何的内容把这个地方填满吗？

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +        homepagephoto = "/static/assets/img/taskboard.jpg"
反对你这个写法。
你的写法应该是这样：取出过去一周的所有活动，filter出上传了照片的活动，从每个活动的照片中随机选择一张，弄成一个list（并且支持点击图片跳转到活动的页面，例如读一下活动id），然后作为你的活动photos的列表。
如果列表为空，那么添加一张default，否则什么都不加。
然后传到前端使用。

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +    weather = urllib.request.urlopen("http://www.weather.com.cn/data/cityinfo/101010100.html").read()
这么写，如果这个网站出问题或者外网访问出问题，有可能会被卡死，这个问题很大。
搜一下djangp ajax写法，ajax是前端js的一个模块，默认异步，你可以先render，然后再这个界面加载出来后在js里面通过ajax向服务器请求天气数据，然后直接处理（甚至可以不用写views.py，因为你本身也是向一个网站请求然后返回json，这个操作js绰绰有余）

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +    start_THEDAY = start_time.day # 前端使用量
前端可以直接使用`start_time.day`吧？

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
>          show_url = False
请直接写成`show_url = True if activity.URL is not None and activity.URL != "" else False # 前端使用量，表示是否展示URL`

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +            summaryphotos = request.FILES.getlist('images')
try请只包裹这一行，不要把那么多内容放到try里面

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +        html_display["warn_message"] = "成功提交活动照片。"
提醒的格式要统一，如果加标点就统一加上，用感叹号也行

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +                pictures.append(request.POST.get("picture5"))
如果是默认预约图片的上传，为什么从request里面读取啊？我没太懂，这些不是很可能没有吗？
并且请写成 `pictures = [request.POST.get("picture" + str(i+1)) for i in range(5)]`

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +                announcephotos = request.FILES.getlist("images")
我更加不理解这个逻辑了。这个到底是在干什么事情呢？这五张图片如果是默认图片为什么这里还有这个逻辑？
我建议的逻辑是这样：
五张默认图片html可以直接从static里面读取，然后不在后端涉及到这方面的逻辑。后端的POST发生在他提交活动的时候，此时如果活动没有上传图片，那么就warning。

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +
允许用户修改活动图片吗？请和展鹏联系下要他加上修改图片的逻辑？并且，如果我不上传随便点击一张，那么应该是支持一个活动只上传一张吧？还是说一个活动必须传满五张呢（我建议不这么做）

2021-08-27 23:44 UTC, YWolfeee commented on app/views.py
> +def make_relevant_notification(application, info):
这个函数应该不是你写的吧？你把上面的全部问题改完后merge最新的develop后再PR吧

2021-08-27 23:44 UTC, YWolfeee commented on templates/activity_add.html
> +                                                        <label>必选：请上传长:宽=16:9左右的图片。如无预告图片可上传，请在下列默认图片中选择一或多张</label>
为什么还有这个要求？

2021-08-27 23:44 UTC, YWolfeee commented on templates/activity_add.html
> +                                                            <img src={% static "assets/img/1.jpeg.jpg" %} class="img-fluid">
请用`{% for %}`搞定

2021-08-27 23:44 UTC, YWolfeee commented on templates/welcome_page.html
> +                            <h2>元培团委</h2>
这一大段删了就好

2021-08-28 03:40 UTC, Sophie-zh commented on app/views.py
> +                pictures.append(request.POST.get("picture5"))
我做成勾选的形式了，一共有5张默认预约图片，负责人勾选若干张；后端读取负责人【是否勾选】，所以如果没有勾选的话就会get None；五张都未勾选的话就会进行提示“必须上传自己的图片或勾选默认图片”

2021-08-28 03:42 UTC, Sophie-zh commented on app/models.py
> +    show_grade = models.BooleanField(default=True)
我也不明白...我这个pr其实只改了几行，只包含了views和welcome.html的修改，但是旧的commit不知为何还存在

2021-08-28 03:43 UTC, Sophie-zh commented on app/models.py
> +    show_grade = models.BooleanField(default=True)
我也不明白...我这个pr其实只改了几行，只包含了views和welcome.html的修改，但是旧的commit不知为何还存在

2021-08-28 03:45 UTC, Sophie-zh commented on app/views.py
> +    ModifyOrganization,
github的问题orzz,改完开个新的试试看吧。它总是把旧版本（已经淘汰了）和新版本（which我和develop里一样）进行比较

2021-08-28 03:46 UTC, Sophie-zh commented on app/views.py
> +    wishes = Wishes.objects.all()[:100]
现在页面的想法是如果没有数据全都写一行“没有此类消息/活动”。

2021-08-28 03:48 UTC, Sophie-zh commented on app/views.py
> +        homepagephoto = "/static/assets/img/taskboard.jpg"
明白了！

2021-08-28 03:49 UTC, Sophie-zh commented on app/views.py
> +    weather = urllib.request.urlopen("http://www.weather.com.cn/data/cityinfo/101010100.html").read()
这个我恐怕得问问学弟hh他对js比较熟悉

2021-08-28 03:53 UTC, Sophie-zh commented on app/views.py
> +                announcephotos = request.FILES.getlist("images")
五张默认图片功能不一，包含活动、讲座、娱乐等；负责人可以根据需要选择对应功能的若干张；也可以自己上传。这里的逻辑是：如果没上传且没勾选图片，进行warning；如果勾选了或者上传了或者两件事都干了，都没问题。

2021-08-28 03:54 UTC, Sophie-zh commented on app/views.py
> +
不允许删除，允许随时随地任何人的添加。现在几张都行，没有一定要五张。

2021-08-28 03:55 UTC, Sophie-zh commented on app/views.py
> +def make_relevant_notification(application, info):
sigh好的，pr前确实这么做了，我改完再试试

2021-08-28 03:57 UTC, Sophie-zh commented on templates/activity_add.html
> +                                                            <img src={% static "assets/img/1.jpeg.jpg" %} class="img-fluid">
啊救命这是什么情况...出问题了orzz这是旧的代码怎么还魂了

2021-08-28 05:41 UTC, closed without merging