问答中心
Yuanpei-Intelligence/YPPF pull request #323
Opened 2021-09-11 15:13 UTC by linhaowei1

做的很丑，需要进一步设计一下这个问答的呈现形式，先实现了功能。
用户主页提问->收通知->进入问答中心->回答->发送信息->查看问答中心/通知，大概是这么个流程

2021-09-11 18:50 UTC, YWolfeee commented
@linhaowei1 给一下截图
@panhongtao07 把12880开起来？我们测试下

2021-09-11 18:52 UTC, YWolfeee requested changes

2021-09-11 18:52 UTC, YWolfeee commented on local_json_template.json
> +        "wechat_url": "http://162.105.210.3:12882/"
这个别改动

2021-09-11 19:05 UTC, linhaowei1 commented
![image](https://user-images.githubusercontent.com/56622542/132958706-aa7c1a60-d921-4936-bde0-869436f7dae9.png)

2021-09-11 19:05 UTC, linhaowei1 commented
![image](https://user-images.githubusercontent.com/56622542/132958716-ae5546c6-c41c-497f-b649-e23630cd5280.png)
![image](https://user-images.githubusercontent.com/56622542/132958722-e3ecc5cb-f970-461f-9635-f03ceb278aa5.png)
![image](https://user-images.githubusercontent.com/56622542/132958731-bd2e3158-930f-45b8-9788-80c5e8b4ae78.png)

2021-09-12 06:45 UTC, XuRuihan commented on app/views.py
> +        if request.POST.get("anwser") is not None:
typo

2021-09-12 07:10 UTC, linhaowei1 commented on app/views.py
> +        if request.POST.get("anwser") is not None:
这个typo是啥意思呀？

2021-09-12 08:29 UTC, YWolfeee commented on app/views.py
> +        if request.POST.get("anwser") is not None:
是说你answer打错了

2021-09-12 10:02 UTC, merged

2021-09-12 11:43 UTC, linhaowei1 commented on app/views.py
> +        if request.POST.get("anwser") is not None:
我去，我所有的answer都打成anwser。。。。。。。。。。英语暴毙