launch_activities
Yuanpei-Intelligence/YPPF pull request #33
Opened 2021-07-23 13:08 UTC by qingzhenduyu

没解决的问题：具体是哪个组织传入的信息还未解决，需要整合后再添加

2021-07-23 15:17 UTC, YWolfeee requested changes

2021-07-23 15:17 UTC, YWolfeee commented on app/models.py
> +    finish = models.DateTimeField("活动结束时间",blank=True,default=datetime.now())
要么统一用finish，要么统一用end

2021-07-23 15:17 UTC, YWolfeee commented on app/models.py
> +    store_YQP = models.FloatField("已募集的元气值", default=0.0)  # 记录收到的元气值的多少
不优雅，这个属性本质上是通过转帐表唯一决定的，我觉得没有必要。

2021-07-23 15:17 UTC, YWolfeee commented on app/models.py
>      year = models.IntegerField("活动年份", default=int(datetime.now().strftime("%Y")))
另外建议把活动的`topic`改成`title`，然后增加地点属性

2021-07-23 15:17 UTC, YWolfeee commented on app/models.py
> +    class TransferStatus(models.IntegerChoices):
为什么叫`TransferStatus`？应该叫`AttendStatus`之类的吧

2021-07-23 15:17 UTC, YWolfeee commented on app/models.py
> +    status = models.IntegerField('学生参与活动状态',choices=TransferStatus.choices, default=2)
default不一定对，如果是投点报名的，default应该是`APPLYING`

2021-07-23 15:17 UTC, YWolfeee commented on app/utils.py
> +def check_time(start_time, end_time):
请注释描述这个函数的功能，它检测的这个`start_time`和`end_time`是报名还是活动本身?

2021-07-23 15:17 UTC, YWolfeee commented on app/utils.py
> +        now_time = datetime.datetime.strptime(str(datetime.datetime.now().date()), '%Y-%m-%d %H:%M:%S')
我没懂，为什么不写`datetime.now()`

2021-07-23 15:17 UTC, YWolfeee commented on app/utils.py
> +def check_time(start_time, end_time):
另外也不要起这种很general的函数名

2021-07-23 15:17 UTC, YWolfeee commented on app/views.py
> +
这几个函数之间到底是什么关系？有什么需要暴露在`urls.py`中？我看`addActivities`在`urls.py`中，但是这里删掉了？
可不可以写一个注释描述一下用户操作的函数流转过程？另外每个函数干了什么能不能在def的时候写一下。
我先看到这里，下面的我现在看不懂（

2021-07-23 15:29 UTC, YWolfeee commented on app/views.py
> +    if request.method == "POST" and request.POST:
`valid, user_type, html_display = utils.xxx`做一个valid的检查

2021-07-23 17:36 UTC, YWolfeee requested changes

2021-07-23 17:36 UTC, YWolfeee commented on app/models.py
> +    power = models.IntegerField("发送权限", default=1)  # 权限：1是给报名者发消息，0是给所有人发消息（暂时如此）
这个字段的作用是什么？我没有理解。
如果你说发送消息的话，自定义消息是由权限系统来决定的，然后全局消息是由组织的leve决定的，不建议引入这个逻辑

2021-07-23 17:36 UTC, YWolfeee commented on app/views.py
> +        return redirect('/index/')  # test
不应该是`/index/`，应该跳回`/welcome/`

2021-07-23 17:36 UTC, YWolfeee commented on app/utils.py
> +    act_end = request.POST["actEdate"] + ' ' + request.POST["actEtime"] + ':00'  # 活动结束时间
这里有很大的问题。你有没有想过，你第一次访问`addActivities`的时候方法是什么？肯定是`get`，只有第二次提交的时候方法才会变成`post`啊。所以你在`addActivities`里面也没有思考这一次究竟是在什么状态下访问，直接要参数会直接报错的

2021-07-23 17:36 UTC, YWolfeee commented on app/utils.py
> +    if_ilegal = 0
你这段问题也太多了。类型的正确性有没有检查过？万一`str`无法转换成`int`怎么办？`places`是不是正整数？元气值的小数点位数是不是只精确到0.1？这些错误统统需要返回提醒的，思考一下你地下室预约的时候如果参数写的不规范会怎么提示。
你这里需要认真思考

2021-07-23 17:36 UTC, YWolfeee commented on app/utils.py
> +
这个方式非常不优美，无论是返回值还是对错误的处理。
我觉得，无论是前面说的get和post的区分还是这个函数调用一个操作函数的返回值和错误的处理，**请你一定认真的看一下`myYQPoint`以及它调用`confirm_transaction`究竟是怎么实现的，都给了你的错误提供了非常好的解决方案**

2021-07-23 17:36 UTC, YWolfeee commented on app/utils.py
> +        month_late = (now_time + datetime.timedelta(days=30))
为什么不能直接写`month_late = datetime.now() + datetime.timedelta(days=30)`？

2021-07-23 17:36 UTC, YWolfeee commented on app/views.py
> +from app.utils import MyMD5PasswordHasher, MySHA256Hasher, check_ac_request
不要这么写，这两个地方只保留加密，你再调用的时候因为`utils`已经被import了，请写`utils.check_ac_request`

2021-07-23 17:36 UTC, YWolfeee commented on app/views.py
> +    capacity = request.POST["capacity"]  # 活动举办的地点，默认是list
你看看注释哈哈哈哈

2021-07-23 17:36 UTC, YWolfeee commented on app/views.py
> +            context["msg"] = "Can not launch this activity, please check time or if activity is reiterated "
这里请直接在ac函数中检查并确定好报错类型，为什么要离得那么远。
另外回传前端请用`html_display`字典，这里面包含了一些需要的信息，在你的
`valid, user_type, html_display = ...`中已经写到了，你这里就往里面添加就好

2021-07-23 17:36 UTC, YWolfeee commented on templates/activity_add.html
> +                                                <h4>填写活动详细信息</h4>
`<h4>详细信息</h4>`

2021-07-23 17:36 UTC, YWolfeee commented on templates/activity_add.html
> +                                                        <label class="custom-control-label" for="customRadioInline2">仅给已报名者发消息</label>
创建活动的时候是没有所谓的报名者的。并且我理解本质上活动发起者会写活动名称地点时间价格简介这些，然后给订阅者发送的消息是会根据填写信息自动模板化发送的。所以这里只需要提醒一下“活动发起后订阅成员会看到提醒”，然后未来这个东西需要扩展成支持修改的，那么那个时候提醒才变成“发送给报名者”
这里就直接是一个活动简介就完了，`power`取消掉

2021-07-23 17:36 UTC, YWolfeee commented on templates/activity_add.html
>          </div>
删掉就好，`base.html`里面有footer

2021-07-24 02:40 UTC, qingzhenduyu commented on app/utils.py
> +        month_late = (now_time + datetime.timedelta(days=30))
1.datetime.now()返回的，例如，2021-07-24 10:39:16.929705
这种样子，最好先期处理为2021-07-24 10:39:17最好

2021-07-24 02:42 UTC, qingzhenduyu commented on app/views.py
> +            context["msg"] = "Can not launch this activity, please check time or if activity is reiterated "
在函数检查里传入一个字典，我会觉得很不优雅doge
在这里统一处理也会比较好看一些
再加上实际要检查的比较多，如果中间掺杂着各种报错信息，感觉很乱

2021-07-24 02:42 UTC, qingzhenduyu commented on templates/activity_add.html
>          </div>
不太清楚要删哪一部分，我问问xq

2021-07-24 08:08 UTC, YWolfeee commented on app/models.py
> +    semester = models.CharField("活动学期", choices=Semester.choices, max_length=15)
我突然意识到这个default有点问题，你可以参考从local_dict里面读取default year和default semester的代码，我没记错的话组织是用的这个

2021-07-24 08:08 UTC, YWolfeee commented on app/models.py
> +    end = models.DateTimeField("活动结束时间", blank=True, default=datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
球球了，`default = datetime.now()`

2021-07-24 10:10 UTC, merged