Modify YQPoint API
Yuanpei-Intelligence/YPPF pull request #37
Opened 2021-07-25 14:19 UTC by pkuGenuine

2021-07-25 17:03 UTC, YWolfeee requested changes

2021-07-25 17:03 UTC, YWolfeee commented on templates/myYQPoint.html
> +                                                                            <i class="	fa fa-rmb"></i>{% widthratio record.amount 10 1%}
这里也不需要

2021-07-25 17:03 UTC, YWolfeee commented on templates/transaction_page.html
> +                                <form action="/startTrans/" method="POST">
这个页面还是要多一个提示是你正在向谁发起转账，方便同学们确认，但是不能修改。

2021-07-25 17:03 UTC, YWolfeee commented on app/views.py
>              recipient_type = "np"
这里的问题和上面一样，你的person_id_id不是username，那个`zzxxxxx`是username

2021-07-25 17:03 UTC, YWolfeee commented on templates/user_left_narbar.html
> +                <a href="/transPage/{{person.person_id_id}}" aria-expanded="false" class="dropdown-toggle">
也修改一下组织的`org_lef_narbar.html`中对应的内容

2021-07-26 00:38 UTC, pkuGenuine commented on app/views.py
> +            record.message = f"Participate Activity {activity.topic}"
为啥挂的时候会自动填写？

2021-07-26 00:41 UTC, pkuGenuine commented on app/views.py
> +                record.status = TransferRecord.TransferStatus.WAITING
感觉花了元气值报名了活动，但没参与上有点奇怪......

2021-07-26 00:44 UTC, pkuGenuine commented on app/views.py
> +                if cnt <= 0:
?

2021-07-26 00:51 UTC, pkuGenuine commented on templates/transaction_page.html
> +                                <form action="/startTrans/" method="POST">
是用了 Name 的

2021-07-26 05:24 UTC, YWolfeee commented on app/views.py
> +            return render(request, "msg.html", context)
`name = recipient.name if hasattr(recipient, 'name') else recipient.oname`

2021-07-26 06:35 UTC, merged