添加长期课程活动定时任务
Yuanpei-Intelligence/YPPF pull request #407
Opened 2022-02-13 03:43 UTC by qingzhenduyu

实现逻辑：
（1）课程活动定时发起，提前量为一周；
（2）定时任务每5min扫一次。
初步测试成功。

2022-02-13 09:18 UTC, YWolfeee requested changes

2022-02-13 09:18 UTC, YWolfeee commented on app/models.py
> +                            null=True,verbose_name="课程每周活动时间")
为什么新加 本来就有活动时间啊

2022-02-13 09:18 UTC, YWolfeee commented on app/scheduler_func.py
> +    )
需要告诉组织是谁在审批

2022-02-13 09:18 UTC, YWolfeee commented on app/scheduler_func.py
> +                              replace_existing=True)
@pkuGenuine

2022-02-13 09:18 UTC, YWolfeee commented on app/scheduler_func.py
> +                    week_time.save()
为什么现在还需要确定周数呢？一直发下去啊，如果组织不需要了直接来一个取消全部就搞定了。不要设置“预计周数”吧

2022-02-13 09:18 UTC, YWolfeee commented on app/scheduler_func.py
> +                    week_time.save()
最后16周有一个学期结束日期，超过这个就停止

2022-02-13 09:20 UTC, qingzhenduyu commented on app/models.py
> +                            null=True,verbose_name="课程每周活动时间")
> 为什么新加 本来就有活动时间啊

因为你要从活动定位到对应的课程时间

2022-02-13 09:22 UTC, qingzhenduyu commented on app/scheduler_func.py
> +    )
默认都是刘欣悦老师，而且，这些定期发布的活动都是默认审批通过的，这的作用只是告诉欣悦老师这门课程这周的活动发布了

2022-02-13 09:23 UTC, qingzhenduyu commented on app/scheduler_func.py
> +                              replace_existing=True)
这个部分是按照之前的逻辑加的，我需要等通过PR399

2022-02-13 09:25 UTC, qingzhenduyu commented on app/scheduler_func.py
> +                    week_time.save()
我和宏弢认为不应该在local_json里添加学校的每学期结束日期

2022-02-14 16:22 UTC, qingzhenduyu commented
增加课程状态改变的定时任务，但尚未测试

2022-02-16 12:59 UTC, qingzhenduyu commented
实现逻辑：

2022-02-16 17:59 UTC, YWolfeee commented on app/scheduler_func.py
> +                              minutes=1,    #TODO 上线之前可修改成每1h一发
从json里面读，你留下这种东西很容易不记得的

2022-02-16 18:02 UTC, YWolfeee commented on app/course_utils.py
> +        assert 0 <= int(type_num) < 5, "课程类型仅包括德智体美劳五种！"
这个错误明显是恶意，不应该和别的放在一起吧

2022-02-16 18:02 UTC, YWolfeee commented on app/course_utils.py
> +    default_photo="/static/assets/img/announcepics/1.JPG"
保证他必须在5张里面选择一张，然后使用这张，而不是默认可以不选然后自动选

2022-02-16 18:05 UTC, YWolfeee commented on app/course_utils.py
> +        courses.update(status=to_status)
上锁，select_for_updated()

2022-02-16 18:06 UTC, YWolfeee commented on app/course_utils.py
> +                        Position.objects.bulk_create(positions)
建议添加一个最终逻辑：给每个至少选上了一门课的同学一个微信说明他们本学期最后选上了哪些课程（annotate）

2022-02-16 18:06 UTC, YWolfeee commented on app/course_utils.py
> +    """字符串转换成时间"""
注释写清楚转换后的格式

2022-02-16 18:26 UTC, YWolfeee commented
先merge 需要解决2个问题
1. 彻底结束选课阶段后需要给每个至少选上一门课的同学发微信告诉他这学期选上了哪些课
2. 图片前端必选（5选1或者上传），后端不做默认

2022-02-16 18:26 UTC, merged

2022-02-17 12:33 UTC, qingzhenduyu commented
> 先merge 需要解决2个问题
> 
> 1. 彻底结束选课阶段后需要给每个至少选上一门课的同学发微信告诉他这学期选上了哪些课
> 2. 图片前端必选（5选1或者上传），后端不做默认

1.每门课程选上了会发通知，而且学生能够通过“我的课程”那里看到所有选上的课