增加取消所有活动的逻辑
Yuanpei-Intelligence/YPPF pull request #431
Opened 2022-02-16 14:03 UTC by qingzhenduyu

2022-02-16 14:36 UTC, qingzhenduyu commented
![image](https://user-images.githubusercontent.com/56719355/154286864-dc03bac0-fc9c-4178-86fe-1170abde253d.png)

2022-02-16 16:56 UTC, YWolfeee requested changes

2022-02-16 16:56 UTC, YWolfeee commented on app/course_utils.py
> +    course_time = activity.course_time
1. 这些代码能不能写一下注释呀？
2. 我看你基本上没做检查和错误处理，是在外部做过了吗？
3. 你写完注释我立刻看
4. schedule_start += 那个逻辑是什么意思？如果出现差为负数怎么办？

2022-02-16 16:56 UTC, YWolfeee commented on app/course_utils.py
> +        activity.course_time.save()
这是不对的，你的提醒内容是不一样的，你应该提醒大家未来的所有课程都被取消了。
此外，确认过别的逻辑吗，只有这个要修改是吗

2022-02-17 11:38 UTC, qingzhenduyu commented on app/course_utils.py
> +    course_time = activity.course_time
4.负数本来就是应该出现的

2022-02-17 11:39 UTC, qingzhenduyu commented on app/course_utils.py
> +        activity.course_time.save()
不对，因为一周只有一次活动被发出来。

2022-02-17 12:02 UTC, qingzhenduyu commented
> 
右上角的x我不建议删除

2022-02-17 12:28 UTC, qingzhenduyu commented
![image](https://user-images.githubusercontent.com/56719355/154481856-13d9219b-5778-4c30-878c-d2caaed8bb1a.png)

2022-02-17 12:34 UTC, YWolfeee commented
> ![image](https://user-images.githubusercontent.com/56719355/154481856-13d9219b-5778-4c30-878c-d2caaed8bb1a.png)
> 

可以！！

2022-02-17 15:17 UTC, merged