每月发放元气值
Yuanpei-Intelligence/YPPF pull request #48
Opened 2021-07-31 09:09 UTC by sunyb-dot

2021-07-31 09:13 UTC, sunyb-dot commented
大概框架是这个样子的，想请学长看一下有没有问题~有问题的话我先修改吧。
还没测试完，估计今晚会push一个测试过了的版本

2021-07-31 09:41 UTC, YWolfeee requested changes

2021-07-31 09:41 UTC, YWolfeee commented on app/models.py
> +        SEMESTER = "按年发放"
加一个按周/2周

2021-07-31 09:41 UTC, YWolfeee commented on app/models.py
> +    org_YQPoint_rate = models.FloatField("组织获得的元气值比例", default=0)
这两个你写成值不要写比例吧

2021-07-31 09:41 UTC, YWolfeee commented on app/scheduler_func.py
> +def monthly_distribute_YQPoint():
你这个时间这样子不就调整不了了？

2021-07-31 09:41 UTC, YWolfeee commented on app/scheduler_func.py
> +    # print(per_to_dis.values('YQPoint')), for debug
我建议你考虑一下增加转账记录是不是更好，相当于批量添加，状态自动设为"完成"之类的

2021-07-31 09:41 UTC, YWolfeee commented on app/scheduler_func.py
> +    # print(per_to_dis.values('YQPoint')), for debug
不过请测试一下速度

2021-08-04 14:18 UTC, YWolfeee commented on app/admin.py
> +>>>>>>> bf2759d670dd7c2772529ed378252014decf1a44
你这些还是没改呀

2021-08-04 14:33 UTC, sunyb-dot commented on app/admin.py
> +>>>>>>> bf2759d670dd7c2772529ed378252014decf1a44
我现在不太知道该如何让这个间隔可变，目前想到的解决方案是
1、写一个网页函数来添加，可是这样每次修改了自动发放的规则之后都要重新调用一遍那个网页函数，管理的有点麻烦。
2、对每个可能的时间间隔都注册一个任务，可能会累赘。

添加了转账记录，测试了2000个自然人+直接从csv内导入的组织，耗时在3~4s，应该是用循环去做那个转账记录的list太慢了。

2021-08-04 14:39 UTC, YWolfeee commented on app/admin.py
> +>>>>>>> bf2759d670dd7c2772529ed378252014decf1a44
> 我现在不太知道该如何让这个间隔可变，目前想到的解决方案是
> 1、写一个网页函数来添加，可是这样每次修改了自动发放的规则之后都要重新调用一遍那个网页函数，管理的有点麻烦。
> 2、对每个可能的时间间隔都注册一个任务，可能会累赘。
> 
> 添加了转账记录，测试了2000个自然人+直接从csv内导入的组织，耗时在3~4s，应该是用循环去做那个转账记录的list太慢了。

去问一下许学长 `bulk_create`怎么用

2021-08-06 14:25 UTC, sunyb-dot commented
用了bulk_create还是比较慢，在2-4s，不知道怎么样还能更快一些。
现在的界面长这个样子
![image](https://user-images.githubusercontent.com/76576839/128525083-6106dc7b-9ace-4294-a572-5b625b3983a8.png)
应该还要补充一个创建的页面，在这里或者创建的页面提交都会注册新的任务，如果已有则会覆盖

2021-08-06 14:26 UTC, sunyb-dot commented
正在速成前端，争取做的好看一点

2021-08-07 10:34 UTC, YWolfeee commented
设置一下superuser才能登录

2021-08-07 18:34 UTC, YWolfeee commented on app/urls.py
> +    path("new_YQP_distribution", scheduler_func.new_YQP_distribute, name="new_YQP_distribution"),
解释一下为什么有那么多需要暴露到前端的页面？

2021-08-08 03:47 UTC, sunyb-dot commented on app/urls.py
> +    path("new_YQP_distribution", scheduler_func.new_YQP_distribute, name="new_YQP_distribution"),
这几个url大致相当于对YQPoint_Distribute类的一个admin界面，添加了每次提交时候检测要不要添加定时任务，想了想觉得好像不太好减少

2021-08-08 03:48 UTC, sunyb-dot commented on app/urls.py
> +    path("new_YQP_distribution", scheduler_func.new_YQP_distribute, name="new_YQP_distribution"),
我有办法把他们合并一下吗qwq

2021-08-09 11:20 UTC, XuRuihan commented on app/models.py
> +>>>>>>> d474936360fd16e151ea7e3d592c34f540662be8
没删干净

2021-08-09 11:20 UTC, XuRuihan commented on app/scheduler_func.py
> +    #     return render(request, "debugging.html", {"message": message})
以后无效的代码就不用注释了，因为github已经保留了历史版本。以下同理

2021-08-09 11:20 UTC, XuRuihan commented on app/urls.py
> +    # path("new_YQP_distribution", scheduler_func.new_YQP_distribute, name="new_YQP_distribution"),
同上，不要有注释代码

2021-08-09 11:20 UTC, XuRuihan commented on app/models.py
> +>>>>>>> d474936360fd16e151ea7e3d592c34f540662be8
没删干净吧，以后不要出现这种问题了。

2021-08-10 07:11 UTC, merged