notification界面的”一键阅读“按钮的添加
Yuanpei-Intelligence/YPPF pull request #531
Opened 2022-03-01 15:24 UTC by jiayueru

<img width="857" alt="a08899ea0206ea9b96401563baf760c" src="https://user-images.githubusercontent.com/97873902/156196952-378932ab-5050-4be7-8088-85302f9c17a8.png">
<img width="892" alt="7bcd8f392aa08601d38707341009704" src="https://user-images.githubusercontent.com/97873902/156196979-45a8629b-dc4a-4706-9292-67414f7ff686.png">

2022-03-01 15:26 UTC, jiayueru commented
> <img alt="a08899ea0206ea9b96401563baf760c" width="857" src="https://user-images.githubusercontent.com/97873902/156196952-378932ab-5050-4be7-8088-85302f9c17a8.png">
> 
> <img alt="7bcd8f392aa08601d38707341009704" width="892" src="https://user-images.githubusercontent.com/97873902/156196979-45a8629b-dc4a-4706-9292-67414f7ff686.png">

之前改color的时候改了两个文件里的颜色，现在又改回来了，这次只修改了”notification.html“

2022-03-02 06:19 UTC, jiayueru commented
好滴谢谢反馈！个人感觉第三点确实，如果移动到待处理的旁边感觉会不太好看，“全标已读”个人感觉稍稍有些奇怪，如果改成“全部设为已读”呢？

2022-03-02 10:17 UTC, Aubrey-Lu commented
> 好滴谢谢反馈！个人感觉第三点确实，如果移动到待处理的旁边感觉会不太好看，“全标已读”个人感觉稍稍有些奇怪，如果改成“全部设为已读”呢？

“全部已读”也行，稍微短一点会比较好；按钮位置的话，我觉得需要放在不那么显眼的地方。也许可以集成附加功能，比如把“全部已读”和以后可能增加的其他功能，都放在一个下拉列表里面，就不会太占地方。（只是一个想法，不一定要现在实现）

2022-03-02 13:33 UTC, jiayueru commented
嗯嗯好滴！我再研究一下~

2022-03-03 05:51 UTC, jiayueru commented
<img width="844" alt="image" src="https://user-images.githubusercontent.com/97873902/156504604-e6c55a28-1101-460c-bb16-a65e418cb705.png">

2022-03-03 11:29 UTC, YWolfeee commented
有一个建议 用好icon。例如，在通知信箱4个字右边加一个眼睛/envelope之类的icon，鼠标悬浮会提示“全部设为已读"。
然后点击这个icon可以写一个onclick = confirm("你确定要将所有未读的知晓类通知设为已读吗？”）
这样就不用专门搞一个按钮，会比较美观。

2022-03-03 11:34 UTC, Aubrey-Lu commented
眼睛其实更像是用来查看详情的，我其实觉得可以用三个点，就是github评论框右上角的这种，代表附加功能；以后有什么新增功能都可以放进去

2022-03-03 11:37 UTC, Aubrey-Lu commented
我觉得通知最好也能支持手动删除，类似浏览记录的删除，可以选择删除多久以前的通知。（只是预想，现在无需实现）

2022-03-04 03:35 UTC, jiayueru commented
@YWolfeee 那学长我就做一个三个点的icon？那是否还需要confirm呢？

2022-03-04 03:54 UTC, YWolfeee commented
> @YWolfeee 那学长我就做一个三个点的icon？那是否还需要confirm呢？

3个点说的是下拉 confirm是防止误触 不同的事情~建议还是要

2022-03-04 04:07 UTC, jiayueru commented
哦哦好滴，我尽快改一下~

2022-03-05 16:39 UTC, jiayueru commented
<img width="158" alt="image" src="https://user-images.githubusercontent.com/97873902/156892142-3d74b18f-4b87-41eb-995d-88831b8c2a5b.png">
虽然感觉还有一丝丝奇怪，就是消息没了confirm的语句还是没变，而且可以不在已读页面删除消息也感觉怪怪的，不过感觉已经比之前好不少

2022-03-06 05:28 UTC, YWolfeee commented
> <img alt="image" width="158" src="https://user-images.githubusercontent.com/97873902/156892142-3d74b18f-4b87-41eb-995d-88831b8c2a5b.png">
> 
> 虽然感觉还有一丝丝奇怪，就是消息没了confirm的语句还是没变，而且可以不在已读页面删除消息也感觉怪怪的，不过感觉已经比之前好不少

你的提示语&这个按钮是否呈现可以考虑根据未读消息的个数来设置呀？

我举个例子，如果未读的消息数等于0，那么全部已读这个按钮就不显示，具体的实现方式可以是 hidden = "{% if xxx %} true {%else %} fasle {% endif %} "之类的（可以参考别的）
又比如，你的confirm提示语可以根据数量来调整对不对？
当然需要注意一个问题，例如进去的时候未读消息是2条，但是这个人都点了知道了（这个知道了用的是js），所以你如果访问后端传过来的未读消息数量可能还是2，这个时候就会出现问题。好的办法是你适当的修改js使得confirm的提示跟着变化，例如没有消息的时候你就直接alert("您的信箱很干净，没有未读消息哦！“）

另外确认一下全部删除的功能是什么含义？具体一点是删除哪一个部分，真删除还是假删除呢？

2022-03-06 06:14 UTC, jiayueru commented
嗯嗯好滴，“另外确认一下全部删除的功能是什么含义？具体一点是删除哪一个部分，真删除还是假删除呢？”这句有点没太看懂orz，另外想问一下如果有消息还没"知道啦"，可以删除嘛？

2022-03-06 09:37 UTC, Aubrey-Lu commented
> 嗯嗯好滴，“另外确认一下全部删除的功能是什么含义？具体一点是删除哪一个部分，真删除还是假删除呢？”这句有点没太看懂orz，另外想问一下如果有消息还没"知道啦"，可以删除嘛？

真删除就是把数据库里的记录删除，假删除是打个标签，只是不显示，数据库里面还是存在；我认为可以真删除，暂时没想到会有什么后果。

2022-03-06 09:39 UTC, Aubrey-Lu commented
是否已读都应该可以删除，就算没有点已读，用户实际上已经看到了；最好加上时间限制，可以选择删除多久以前的通知。

2022-03-06 11:33 UTC, Aubrey-Lu commented
btw，不要把local_json_template.json删掉

2022-03-06 13:38 UTC, YWolfeee commented
> 是否已读都应该可以删除，就算没有点已读，用户实际上已经看到了；最好加上时间限制，可以选择删除多久以前的通知。

这个我觉得暂时可以不做，不然有点太困难而且太乱了，可以等产品的设计；
我现在的建议就是，未读的部分可以一键已读；已读的部分可以一键删除；我也觉得真删除应该是可以的

2022-03-08 05:57 UTC, jiayueru commented
想问一下我是应该根据消息数量去hidden“全部按钮”，还是去更改confirm的内容呢？

2022-03-08 08:20 UTC, Aubrey-Lu commented
filter+count得到数量，然后做个判断就行；如果没有新消息就让“全部已读”不激活，有的话就根据数量给出confirm的内容；“全部删除”类似。

2022-03-19 03:50 UTC, jiayueru commented
<img width="1040" alt="26f72d15cc18209e7a4dd1de2c3b17b" src="https://user-images.githubusercontent.com/97873902/159105572-9bf9ae8e-efd3-422b-bb9e-a801aa707edd.png">
在没有可读消息和可以删除的消息的时候confirm

2022-03-20 02:40 UTC, YWolfeee commented
> <img width="1040" alt="26f72d15cc18209e7a4dd1de2c3b17b" src="https://user-images.githubusercontent.com/97873902/159105572-9bf9ae8e-efd3-422b-bb9e-a801aa707edd.png">
> 在没有可读消息和可以删除的消息的时候confirm

确认一下 已读和删除的消息具体是哪些呀 你的filter语句可不可以发一下~

2022-03-20 05:22 UTC, jiayueru commented
<img width="467" alt="image" src="https://user-images.githubusercontent.com/97873902/159149397-a11d1a99-a0f6-4c06-aa14-dc7fa078b097.png">
好滴！不知道这样是不是对滴orz

2022-03-20 07:27 UTC, YWolfeee requested changes
这个实现在效率上存在问题。试想这位同学有100条消息，你现在的实现，如果我理解的没错，应该是loop调用每一条消息的read()? 这里read 里面的await save_read是向服务器发送一条请求，服务器执行【已读此消息】，然后返回结果；那么这样的实现就会造成100次网络访问的开销，相当于你走了100次网络访问的延迟。
一个合理的操作是：将save_read修改为对【给定的一个消息集合设定为已读】，那么此时一次互联网访问开销就可以完成。
别的minor issue写在代码里了~加油！

2022-03-20 07:27 UTC, YWolfeee commented on app/views.py
> +
不要做这种修改

2022-03-20 07:27 UTC, YWolfeee commented on local_json_template.json
> -    },
不要删除这个文件

2022-03-20 07:27 UTC, YWolfeee commented on templates/notifications.html
> +}
为什么要右端对齐？

2022-03-20 12:56 UTC, jiayueru commented
嗯嗯收到！俺再研究一下！

2022-04-01 13:59 UTC, jiayueru commented
求助！如果我想给后端传递“已读消息的集合”是以怎样的形式比较好呢？我看fetch body里面需要是key-value这样的形式？所以如果我把所有需要修改的id放到一个数组里再传就不行吗？

2022-04-02 11:49 UTC, YWolfeee commented
> 求助！如果我想给后端传递“已读消息的集合”是以怎样的形式比较好呢？我看fetch body里面需要是key-value这样的形式？所以如果我把所有需要修改的id放到一个数组里再传就不行吗？

你可以假设value == -1表示全集合

2022-04-04 05:57 UTC, jiayueru commented
<img width="512" alt="image" src="https://user-images.githubusercontent.com/97873902/161481964-98ab1824-a976-4c94-9776-165a94e8eb60.png">
<img width="744" alt="image" src="https://user-images.githubusercontent.com/97873902/161482034-c29202bd-373b-46d0-9fd7-25e9003e82eb.png">
<img width="743" alt="image" src="https://user-images.githubusercontent.com/97873902/161482072-fe434e5b-c9e9-4595-ac8d-e745c29c3fa3.png">
views.py里面的try和except里的warn code不太会写orz...

2022-04-05 03:28 UTC, linhaowei1 commented
> <img alt="image" width="512" src="https://user-images.githubusercontent.com/97873902/161481964-98ab1824-a976-4c94-9776-165a94e8eb60.png">
> 
> <img alt="image" width="744" src="https://user-images.githubusercontent.com/97873902/161482034-c29202bd-373b-46d0-9fd7-25e9003e82eb.png">
> 
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/97873902/161482072-fe434e5b-c9e9-4595-ac8d-e745c29c3fa3.png">
> 
> views.py里面的try和except里的warn code不太会写orz...

这块原始代码有点问题，返回jsonresponse之后，html_display的内容就不会被渲染出来。所以设置了也没用。
如果我们希望返回提示语，需要返回render，前端会提取locals()的变量，自动呈现html_display的内容（可以看这部分的前端代码）。所以需要把这里所有的返回jsonresponse改成return render(...)（具体参数可以参考一下所有views里的return值）
其次，我不记得notification_status_change有没有“同时修改多个notification”的版本？就是传入一个notification的list，同时修改。如果有的话就不需要调用多次notification_status_change，因为这个相当于每次会返回一个context标识是否修改成功，如果有某个通知修改失败，会出现“一些通知状态被修改了，遇到了这个失败的，后面的通知都不修改了，直接跳到except”。如果没有同时修改多个notification的函数接口，可以给这个修改过程做成原子操作：with transaction.atomic()，保证一次能全部修改，否则修改失败回滚到初始状态（什么都没改）。
改完了这个两个地方，warn_code就按你现在写的就行，不用改了。

2022-04-30 15:41 UTC, jiayueru commented
<img width="755" alt="image" src="https://user-images.githubusercontent.com/97873902/166112379-597517ab-a5fd-4037-ad9e-e7b8d891e66c.png">
这里不知道with transaction.atomic()加的位置是否正确？这样改能否解决目前的问题呢？

2022-05-02 06:55 UTC, linhaowei1 commented
> <img alt="image" width="755" src="https://user-images.githubusercontent.com/97873902/166112379-597517ab-a5fd-4037-ad9e-e7b8d891e66c.png">
> 
> 这里不知道with transaction.atomic()加的位置是否正确？这样改能否解决目前的问题呢？

嗯我检查了一下notification_status_change这个函数，确实没有批量处理的版本，预计后期会写一下。
目前的实现，我觉得还是把with transaction.atomic()去掉吧，我感觉这么加也怪怪的。然后在for循环里加一个判断
```python
for note in notification_set:
    # change status... 省略部分code
    if context["warn_code"] == 1:
       break
```
这个实现并不是非常优雅，我觉得后期需要加一个工具函数来批量处理notification的状态。如果你想写可以后面写一下，不过这边可以暂时先这么改，然后加一个TODO的注释，让这个feature先上线。

2022-07-07 06:28 UTC, jiayueru commented
![image](https://user-images.githubusercontent.com/97873902/177706056-baadb547-890a-4c32-b5da-e128f983c069.png)
![image](https://user-images.githubusercontent.com/97873902/177706079-c970ffc5-1503-4126-9f81-10779241e493.png)
try 里面warncode和warn message不知到如何加

2022-07-18 13:03 UTC, linhaowei1 commented
@jiayueru 
这个pr我建议你先关掉，然后重新开一个新的，clone现在的仓库，在上面做改动。不然这个改动太多了，merge进去会出问题。
把notification的状态修改改成批量处理吧（按照notification_status_change的逻辑，类似写一下），给notification_status_change加一个同时传入多个id的版本，然后在这里面调用它，context的warn_code和warn_msg就可以直接读取这个函数返回的值。

2022-07-19 03:19 UTC, jiayueru commented
嗯嗯好的，收到！

2022-07-19 03:23 UTC, closed without merging