导入数据优化+人事变动功能实现
Yuanpei-Intelligence/YPPF pull request #55
Opened 2021-08-01 19:01 UTC by XuRuihan

1. 导入数据的速度非常慢，最大瓶颈在于Django默认的加密算法迭代次数比较多，iterations=260,000，因此 `user.set_password()` 非常慢。测试的时候先采用千分之一的迭代次数，可以大大缩短导入数据的时间。
2. 其次将依次导入改进为批量导入，进一步优化。但总的瓶颈还是上一条。
3. 人事变动功能目前实现了申请加入组织+组织审核，个人端通过通知功能获得各种反馈，效果还不错；组织端仿照YQPoint新建了一个专门处理人事变动的页面。关于交接申请功能还没想好从哪个接口进去，后端逻辑已经实现了但可能有些小 bug。
4. 关于 hasher 部分，`app.utils` 太臃肿了，我在 `boottest/` 路径下新建了 `hasher.py` 文件，把我们自建的加密方法都放在这里了。也就是把 `app.utils` 里的加密算法都放到了 `boottest.hasher` 里。
5. 今天太晚了，前端截图我回头发上来。

2021-08-02 11:18 UTC, YWolfeee commented
冲突了 resolve下！

2021-08-02 17:03 UTC, YWolfeee requested changes
comment完了，你可能要尽快改，因为你的修改很多会影响蛮多人的2333

2021-08-02 17:03 UTC, YWolfeee commented on app/views.py
> +        oid = request.POST["oid"]
为什么这里oid不用来get组织，又多一个oname？

2021-08-02 17:03 UTC, YWolfeee commented on app/views.py
> +    application, created = Position.objects.get_or_create(person=me, org=org, pos=2)
这个创建非常不对，申请加入组织的人应该是可以选择`pos`等级的，而且你这个也没有把已经在职的晋升做出来。还是说你做退出→重新进入？anyway，申请假如未必是2，因为每个`otype`的pos个数都不一定一样233

2021-08-02 17:03 UTC, YWolfeee commented on app/views.py
> +        contents = ["申请已取消", "申请已取消"]
你如果想支持取消申请的话，这个按钮可能会有点复杂？

2021-08-02 17:03 UTC, YWolfeee commented on app/views.py
> +        contents = ["申请已取消", "申请已取消"]
我建议这个页面的逻辑再想想吧2333

2021-08-04 15:03 UTC, XuRuihan commented on app/models.py
> +        related_name="position",
我没改啊，但我pull的最新版里没有看到position_set？我只在views.py里看到了一个position_set
我改成 position_set 吧，统一一下。

2021-08-04 15:03 UTC, XuRuihan commented on app/models.py
> +        to_field="organization_id",  # 同上
那我把to_field删掉了

2021-08-04 15:20 UTC, XuRuihan commented on app/models.py
> +        DEPART = "离开"
就是离职的意思，曾经是在职，现在已经不在组织内了。不过这个字段和withdraw好像有点重复，我删掉了。

2021-08-04 15:21 UTC, XuRuihan commented on app/views.py
> +        contents = ["申请已取消", "申请已取消"]
这个页面我还没写呢。。我也没想好怎么实现这个功能，就是先写了个if在这

2021-08-04 15:27 UTC, XuRuihan commented on app/models.py
> -    endbefore = models.SmallIntegerField("报名截止于", choices=EndBefore.choices, default= EndBefore.oneday)
没删，自动格式化了，代码在下面

2021-08-04 15:32 UTC, XuRuihan commented on boottest/settings.py
> +
我也知道存在这个问题，但是我测试的时候每次导入都巨慢无比。。。忍受不了。。
算了这段代码我注释掉吧。。以后的PR里都保证这几行是注释掉的

2021-08-04 15:33 UTC, XuRuihan commented on boottest/settings.py
> +
（其实我加了if DEBUG应该问题不大，线上部署的时候不会用DEBUG版本）

2021-08-05 15:08 UTC, XuRuihan commented on app/views.py
> +    issued_status = Q(status=Position.Status.INSERVICE) | Q(status=Position.Status.DEPART)
加了activated

2021-08-05 15:09 UTC, XuRuihan commented on app/views.py
> +        record.job_name = me.otype.job_name_list[record.pos]
改好了

2021-08-05 15:09 UTC, XuRuihan commented on app/views.py
> +def verify_personnel_mobilization(request):
改好了

2021-08-05 15:09 UTC, XuRuihan commented on app/views.py
> +    application.save()
加了

2021-08-05 15:09 UTC, XuRuihan commented on app/urls.py
> +    path("applyPosition/<str:oid>", views.apply_position, name="applyPosition"),
是

2021-08-05 15:10 UTC, XuRuihan commented on app/views.py
> +    application, created = Position.objects.get_or_create(person=me, org=org, pos=2)
现在可选pos等级，不选默认pos=10（也就是保证是成员）

2021-08-05 15:10 UTC, XuRuihan commented on app/views.py
> +        contents = ["申请已取消", "申请已取消"]
先删掉了

2021-08-05 15:11 UTC, XuRuihan commented on app/views.py
> +    issued_status = Q(status=Position.Status.INSERVICE) | Q(status=Position.Status.DEPART)
在职状态和申请分开了

> 这个不是`issued_list`吧，如果一个人一开始就是`INSERVICE`的话根本不存在处理这一环节。我觉得一个`Position`的在职状态和处理逻辑应该分开，例如你有一个status表示`在职/离开/待处理`，然后有一个表示申请状态`申请加入/申请退出/已经通过/已经拒绝/无申请流程`，天降的话就是在职状态为在职，申请状态为无申请流程，然后你的pending就是`status=待处理`，`issued_list`就是`me.position.all().exclude(pending).filter(申请状态!=无申请流程`

2021-08-05 15:12 UTC, XuRuihan commented on app/views.py
> +    issued_status = Q(status=Position.Status.INSERVICE) | Q(status=Position.Status.DEPART)
加了activated()
> 还要考虑一下学期，不应该看到去年的吧？

2021-08-05 15:12 UTC, XuRuihan commented on app/views.py
> +@login_required(redirect_field_name="origin")
好

2021-08-05 15:12 UTC, XuRuihan commented on app/views.py
> +        oid = request.POST["oid"]
改好了

2021-08-05 15:43 UTC, YWolfeee commented on app/views.py
> +    user = User.objects.get(id=int(oid))
这一行代码有可能报错，你可能需要`try`包裹下

2021-08-05 15:52 UTC, YWolfeee commented on app/views.py
> +    warn_duplicate_message = "There has already been an application of this state!"
就建议如果有问题直接返回html用提示来伺候

2021-08-06 04:50 UTC, XuRuihan commented on app/views.py
> +    warn_duplicate_message = "There has already been an application of this state!"
我用了啊，只是后面好多地方会用到相同的错误提醒，这里就用一个变量代替了。这里并没有出现错误，2132行的try里面才会出现这种错误。

> 如果我没记错，这几个页面都有统一的提醒格式，应该是
> `html-display["warn_code"] = 1`
> `html_display["warn_message"] = "xxx"`

2021-08-06 04:54 UTC, XuRuihan commented on app/views.py
> +        apply_pos = int(request.POST.get("apply_pos", 10))
写`10`相当于如果不传apply_pos参数的话，默认当成员处理。写`None`的话处理起来不是很麻烦hhhh

2021-08-06 05:10 UTC, merged