书院课程和反馈数据导出
Yuanpei-Intelligence/YPPF pull request #569
Opened 2022-07-19 08:48 UTC by vassagoP

2022-07-19 09:06 UTC, vassagoP commented on app/data_export.py
> +    print(feedbacks)
forget to delete line113,114

2022-07-19 09:09 UTC, vassagoP commented on app/data_export.py
> +    print(feedbacks)
solved now

2022-07-19 09:09 UTC, vassagoP commented on app/data_export.py
> +    print(courses)
solved now

2022-07-19 09:35 UTC, pkuGenuine commented on app/data_export.py
> +            hash_func(str(person.peron_id.name)) if hash_func is not None \
首先用 name 肯定是不好的，因为会有重名。
然后，是不是可以用 group by 降低一下查询的次数。这样每个同学都需要查询一次，效率比较低。

2022-07-19 09:39 UTC, pkuGenuine commented on app/data_export.py
> +    for person in all_person:
同理，试试 group by 吧

2022-07-20 13:50 UTC, pkuGenuine commented on app/data_export.py
> +    feedbacks = pd.DataFrame(columns=('姓名', '学号', '提交反馈数', '已解决反馈数'))
然后对学号脱敏

2022-07-20 14:56 UTC, vassagoP commented on .gitignore
> -*.sh
习惯性使用git add .了，非常抱歉

2022-07-21 13:07 UTC, panhongtao07 commented on app/data_export.py
> +                semester: CharField = None,
int char

2022-07-21 13:26 UTC, panhongtao07 requested changes

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +                     **relate_filter_kws))).order_by('person_id__username')
修改下格式，不要order_by

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +        courses.loc[len(courses.index)] = [
使用enumerate，len太慢了

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +            CourseRecord.objects.filter(**filter_kws,person=person).count(),  # 总门数
在annotate写

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +                               else person.person_id,    # 学号
person_id是对象，用str

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +                else person.record_hours + person.invalid_hours     # 学时
is写法不好

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +                             feedback__solve_status=0,
status类型是不是不太对

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +        feedbacks.loc[len(feedbacks.index)]=[
同样的问题

2022-07-21 13:26 UTC, panhongtao07 commented on app/data_export.py
> +    return feedbacks
回车

2022-07-22 15:39 UTC, pkuGenuine commented on app/data_export.py
> -    'org_position_data',
为什么这里会有修改呢，是出现过 conflict 吗

2022-07-22 15:40 UTC, pkuGenuine commented on app/data_export.py
> -    'org_position_data',
改一下吧，org 比 orga 看着舒服很多，下面的函数名也可以改

2022-07-22 15:43 UTC, pkuGenuine commented on app/data_export.py
> +            ]
这个缩进有点怪

2022-07-22 16:20 UTC, pkuGenuine approved these changes

2022-07-22 16:27 UTC, panhongtao07 approved these changes

2022-07-22 16:30 UTC, merged