长期预约视图函数
Yuanpei-Intelligence/YPPF pull request #570
Opened 2022-07-20 03:44 UTC by Aubrey-Liu

2022-07-23 02:47 UTC, Aubrey-Liu commented
暂时还不需要review，只是用来follow进度与对接的。当然，很欢迎给出修改建议。

2022-07-27 13:42 UTC, Aubrey-Liu commented
<img width="1440" alt="Screen Shot 2022-07-27 at 9 11 08 PM" src="https://user-images.githubusercontent.com/72335144/181261775-aa902f7b-c2f4-45a2-a4fc-c0bbf38e9350.png">
<img width="1440" alt="Screen Shot 2022-07-27 at 9 14 54 PM" src="https://user-images.githubusercontent.com/72335144/181261800-37ae3116-1f4e-47d2-aae4-0516b
<img width="1440" alt="Screen Shot 2022-07-27 at 9 15 06 PM" src="https://user-images.githubusercontent.com/72335144/181261823-0251f5c0-0c75-4a04-82fe-09f76e7b4293.png">
3357911.png">

2022-07-27 13:44 UTC, Aubrey-Liu commented
<img width="1440" alt="Screen Shot 2022-07-27 at 9 44 14 PM" src="https://user-images.githubusercontent.com/72335144/181262372-2033c9a9-c847-4770-964d-a435b7944517.png">

2022-07-28 14:54 UTC, panhongtao07 requested changes
看地下室代码太累啦

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/models.py
> +            self.longtermappoint.save()
不建议做这个关联，长期预约中的其它预约并没有取消

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/utils/web_func.py
> +def get_dayrange(span:int=7, start_week:int=0) -> list:
偏移的是天数会不会更好，这个函数理论场合似乎更泛化

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +    get_participant, identity_check, is_org
加个逗号，另外is_org应该通过数据库增加一列（有没有长期预约权限）的方法，通过模型控制权限

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +def admin_index(request):  # 我的账户也主函数
注释直接改成个字符串吧（怎么还有错字）

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +        appoint = Appoint.objects.get(Aid=appoint_info['Aid'])
类似的可以改为一个utils函数2display，我接下来交给其他同学

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +                                 int(room_object.Rstart.minute >= 30)
这一段整体都缩进了，不太好看修改，这里不如分开写两行

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +                             second=59))
加一个TODO，之后修改

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +            timesection['status'] = 0
原有注释：# 0可用 1已经预约 2已过
请加一个TODO，之后我一起修改这个意义不清的约定

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +                                 int(room_object.Rstart.minute >= 30)
此处逻辑我认为可以重写，这两个temp没什么意义

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +            if datetime.now().strftime("%a") == appoint_params['weekday']:
此处的判断已过时，需要修改，加个start_week判断吧

2022-07-28 14:54 UTC, panhongtao07 commented on Appointment/views.py
> +                            org=get_participant(request.user),
用appoint.major_student吧

2022-07-29 06:21 UTC, panhongtao07 requested changes
发现两个安全漏洞

2022-07-29 06:21 UTC, panhongtao07 commented on Appointment/views.py
> +        start_week = int(start_week)
start_week作为前端参数不能信任，应该保证只在0和1之间

2022-07-29 06:21 UTC, panhongtao07 commented on Appointment/views.py
> +        # 检查预约次数
start_week times interval都需要检查，在后续的

2022-07-29 07:18 UTC, Aubrey-Liu commented on Appointment/models.py
> +            self.longtermappoint.save()
> 不建议做这个关联，长期预约中的其它预约并没有取消

我觉得这个没有问题，因为长期预约中的其他预约是不和长期预约本身关联的，如果不改变模型的话

2022-07-29 11:34 UTC, panhongtao07 requested changes

2022-07-29 11:34 UTC, panhongtao07 commented on Appointment/views.py
> +
需要检查长期预约总数

2022-07-29 13:09 UTC, panhongtao07 approved these changes

2022-07-29 13:11 UTC, merged