task23_元培书房搜索结果页面的后端数据准备
Yuanpei-Intelligence/YPPF pull request #577
Opened 2022-07-26 09:32 UTC by cqkmxpr

1.yp_library/models.py：对书房相关的表做了一些微调
（1）LendRecord表的return_time列允许为空，因为借出未还的书不知道还书时间
（2）Book表的returned列default值改为True，因为系统刚启用时应该大部分书是未借出的

2.boottest/settings.py：在INSTALLED_APPS加入yp_library

3.yp_library/views.py：完成了用于图书检索页面的search函数
（1）关于权限：沿用了yppf的login_required和check_user_access这两个装饰器确保用户已登录。目前还要求登录账号是自然人（而非组织）并且有关联的Reader，否则返回主页面并提示'请使用个人账户登录!'或'您的学号没有关联任何书房账号!'。如果产品那边可以允许组织账号或没有创建书房Reader的个人账号查询馆藏的话，可以再做调整。
（2）关于检索方式：设置了["identity_code", "title", "author", "publisher", "returned"]这五个条件，相互之间是“与”的关系（留空就是不使用该条件）。前四个是用contains查找即包含即可；如果在前端勾选“只看在馆书籍”则要求returned=True否则对returned无要求。特别地，没有要求这些条件至少有一个不为空，也就是说可以通过不输入任何条件查看所有书目
（3）关于前端展示：搜索框和搜索结果包含的信息如图所示（为了避免和其他pr冲突，这个简易的前端代码没有放上来）
![20809d517319ff2641b9eb6eb825124](https://user-images.githubusercontent.com/60976065/180973299-cf1df52d-3d7e-4fdd-9357-1e531baa5d87.jpg)

4.yp_library/utils.py：工具函数
（1）get_readers_by_user：根据学号寻找与user关联的reader，要求必须为个人账号且账号必须通过学号关联至少一个reader，否则抛出AssertionError。在图书检索、查看个人借阅记录中都会使用。
（2）search_books：根据给定的属性查询书。除了views.py中提到的五个条件外还允许使用book的id（int的精确匹配），不过由于id没有什么现实意义，用它查的可能性不大，就没有在views.py里使用id这个查询条件。

5.yp_library/test/test_search.py：对utils.py的search_books函数进行了简单的测试

2022-07-26 09:54 UTC, SouthwestWindQ commented on yp_library/utils.py
> +                query &= Q(returned=q)
感觉这样写很奇怪，循环像是形同虚设……我建议query_list直接改为字典类型（views.search那边准备好），这一段就改为一个个并列的if？

2022-07-26 09:54 UTC, SouthwestWindQ commented on yp_library/utils.py
> +    assert len(query_list) == 6
为什么要assert？

2022-07-26 10:15 UTC, cqkmxpr commented on yp_library/utils.py
> +                query &= Q(returned=q)
ok我改一下

2022-07-26 10:16 UTC, cqkmxpr commented on yp_library/utils.py
> +    assert len(query_list) == 6
主要是怕别的地方用到这个函数，按原来的写法得保证query_list有六个元素且分别对应那六个条件，改成dict应该就不用了

2022-07-26 11:46 UTC, pkuGenuine commented on yp_library/models.py
> +    return_time = models.DateTimeField("还书时间", blank=True, null=True)
Viewer Reference: https://stackoverflow.com/questions/8609192/what-is-the-difference-between-null-true-and-blank-true-in-django

2022-07-26 11:51 UTC, pkuGenuine commented on yp_library/utils.py
> +    return my_readers
我觉得直接返回一个 reader 对象是不是更好？如果 QuerySet 不唯一，就返回 '您的学号关联到多个书房账号，请联系书房同学处理'

2022-07-26 12:14 UTC, pkuGenuine commented on yp_library/utils.py
> +    return my_readers
还是先保留吧，也不会太麻烦

2022-07-26 12:15 UTC, pkuGenuine commented on yp_library/views.py
>  def welcome(request):
welcome 也应该有个搜索页面

2022-07-26 12:52 UTC, pkuGenuine commented on yp_library/views.py
> +import boottest.global_messages as my_messages
有点没懂为啥要有个 my_message 呢 2333

2022-07-26 12:53 UTC, pkuGenuine commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
这种全匹配的方式对用户来说不够友好，能不能想办法支持模糊查询呢。比如查“数学”也能得到“数学分析”

2022-07-26 12:55 UTC, pkuGenuine commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
可能需要一些调研，然后现有的一些搜索功能或许可以参考

2022-07-26 12:57 UTC, cqkmxpr commented on yp_library/utils.py
> +    return my_readers
好的

2022-07-26 12:57 UTC, cqkmxpr commented on yp_library/views.py
>  def welcome(request):
好的我加一下

2022-07-26 12:58 UTC, pkuGenuine requested changes
主要看下怎么支持更用户友好的搜索方式，节奏可以慢一点

2022-07-26 12:58 UTC, cqkmxpr commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
现在查“数学”是能得到“数学分析”的，是指查“数分”得到“数学分析”吗？我去研究一下

2022-07-26 12:59 UTC, cqkmxpr commented on yp_library/models.py
> +    return_time = models.DateTimeField("还书时间", blank=True, null=True)
这个没太理解...我看stackoverflow的回答里面说DateTimeField通常是null和blank都设为True呀，是要把blank改为false吗？

2022-07-26 13:02 UTC, cqkmxpr commented on yp_library/views.py
> +import boottest.global_messages as my_messages
这个包只在my_messages.transfer_message_context(request.GET, frontend_dict, normalize=True)用到了，我直接copy的之前的代码就没注意hhh我改成直接import那个函数吧

2022-07-26 15:01 UTC, pkuGenuine commented on yp_library/models.py
> +    return_time = models.DateTimeField("还书时间", blank=True, null=True)
这个算是“为什么这样改”的说明啦，作为 viewer 可以参考一下的意思

2022-07-26 15:03 UTC, cqkmxpr commented on yp_library/models.py
> +    return_time = models.DateTimeField("还书时间", blank=True, null=True)
哦哦好的好的

2022-07-26 15:05 UTC, pkuGenuine commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
哦哦，我傻了。我觉得暂时不用支持 “数分” 到 “数学分析”。

2022-07-26 15:07 UTC, pkuGenuine commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
或许可以支持一个“全关键词搜索”？就是比如用户搜 "aaa"，不管书名作者还是出版社，包含 "aaa" 的都给出来？

2022-07-26 15:09 UTC, pkuGenuine reviewed
再加一个“全关键词搜索”就该就好了。或许可以改一下 POST 的形式

2022-07-26 15:09 UTC, cqkmxpr commented on yp_library/views.py
> +            query_list.append(["returned", ""])
好的，明天我改一下

2022-07-26 15:11 UTC, cqkmxpr commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
okk我明天改一下

2022-07-27 03:19 UTC, cqkmxpr commented on yp_library/views.py
> +            query_list.append(["returned", ""])
已整合为utils.py的get_query_dict函数

2022-07-27 03:21 UTC, cqkmxpr commented on yp_library/utils.py
> +def search_books(query_dict: dict) -> QuerySet:
已添加全关键词搜索功能，如图
![ce01a1b9f9ea5bafe91fcfb3045594a](https://user-images.githubusercontent.com/60976065/181153505-5bf3a100-8369-4a03-b358-4fb2962973d8.jpg)
上图为Key_words搜索“数学”的结果

2022-07-27 15:49 UTC, pkuGenuine commented on yp_library/utils.py
> +    my_readers = Reader.objects.filter(
为什么要加一个 "my" 的前缀呢

2022-07-27 15:53 UTC, cqkmxpr commented on yp_library/test/test_search.py
> +    def setUp(self):
收到

2022-07-27 15:54 UTC, pkuGenuine commented on yp_library/utils.py
> +    query_list = [[k, post_dict[k]]
为什么不直接用 dict 而是把 list 转成 dict 呢

2022-07-27 15:57 UTC, cqkmxpr commented on yp_library/utils.py
> +    my_readers = Reader.objects.filter(
也没啥特别的原因，就是想表示“我的学号对应的readers”，删掉也行

2022-07-27 15:58 UTC, pkuGenuine commented on yp_library/views.py
> +        frontend_dict["search_results_list"] = search_books(query_dict)
不好意思我想错了，welcome 界面不用接收 post 请求，这里改回去吧......
实在抱歉

2022-07-27 16:00 UTC, cqkmxpr commented on yp_library/utils.py
> +    query_list = [[k, post_dict[k]]
一开始是直接用的list，我改成dict的时候就顺手这么写了hhh我改一下吧

2022-07-27 16:00 UTC, cqkmxpr commented on yp_library/views.py
> +        frontend_dict["search_results_list"] = search_books(query_dict)
哦哦好的，没事没事~

2022-07-27 23:59 UTC, pkuGenuine approved these changes

2022-07-28 00:00 UTC, merged