元培书房还书提醒
Yuanpei-Intelligence/YPPF pull request #598
Opened 2022-08-08 06:06 UTC by vassagoP

2022-08-08 06:07 UTC, vassagoP commented on app/data_export.py
>      return person_frame
这里非常奇怪，本地以及进入编辑模式后是有最后空行的，但保存退出后没有

2022-08-08 09:18 UTC, SouthwestWindQ commented on yp_library/utils.py
> +                                               timedelta(days=1))
这个地方看着有点怪，改成下面的形式会不会好一些？40-42行及43-45行同理
```python
one_day_before = LendRecord.objects.filter(
    returned=False, due_time=cr_time - timedelta(days=1)
)
```

2022-08-08 09:18 UTC, SouthwestWindQ commented on yp_library/utils.py
> +    URL = f"/lendinfo/"
这里字符串前面应该不用加f

2022-08-08 09:18 UTC, SouthwestWindQ commented on yp_library/utils.py
> +        receivers.append(record.reader_id.student_id)
这个地方如果出现重复（比如一个人同时借好几本，现在即将逾期）会出问题吗？

2022-08-08 09:18 UTC, SouthwestWindQ commented on yp_library/utils.py
> +    returned_records_list.sort(key=lambda r: r['return_time'], reverse=True)  # 已完成记录按照归还时间逆序排列
和下面重复？可以删除了

2022-08-08 09:22 UTC, SouthwestWindQ commented
还有一个问题：这个pr的commit太多了，可否整理一下？我之前尝试过的做法是直接删除本地分支，直接拉取yppf远程的最新分支，再将本地的分支push --force到自己的repo；或者你也可以拉一个新分支，在新分支上修改，再request从新分支到yppf/develop的pull。我还尝试过rebase但貌似不太行，你也可以试试

2022-08-08 09:24 UTC, SouthwestWindQ commented on app/data_export.py
>      return person_frame
> 这里非常奇怪，本地以及进入编辑模式后是有最后空行的，但保存退出后没有

这个好像是本来有2个空行然后删了一个空行？我觉得问题不大

2022-08-08 10:46 UTC, vassagoP commented on yp_library/utils.py
> +        receivers.append(record.reader_id.student_id)
这个我没试过，但因为函数是对每条借阅记录独立操作的，所以应该会给借阅者发送多条通知

2022-08-08 11:38 UTC, pkuGenuine commented on yp_library/utils.py
> +    ]
尽量避免这种无意义的改动

2022-08-08 11:39 UTC, pkuGenuine commented on yp_library/utils.py
> +def bookreturn_notification():
是否能做一些函数拆分呢，这种大片的代码读起来并不友好

2022-08-09 08:51 UTC, SouthwestWindQ commented on yp_library/utils.py
> +def bookreturn_notification():
> 好的，请问我新添加一个函数days_reminder(n: int)，接收参数为逾期天数，功能为发送提醒，在bookreturn_notification()中调用四次会好一些吗

可以设置一个工具函数，该接收借阅记录queryset和通知内容，执行批量发通知的功能。然后在这个函数中依次调用该工具函数4次。可以filter一次后就调用该工具函数一次，或许整个函数会更加齐整。

2022-08-12 13:33 UTC, pkuGenuine commented on app/data_export.py
> +from typing import Callable
这个文件已经删掉了

2022-08-12 13:37 UTC, pkuGenuine commented on yp_library/utils.py
> +    for send_mission in send_dict:
这个能跑通嘛

2022-08-12 13:37 UTC, pkuGenuine commented on yp_library/utils.py
> +
空行不要

2022-08-12 13:37 UTC, pkuGenuine commented on yp_library/utils.py
> +    for send_mission in send_dict:
for k, v in send_dict.items()

2022-08-12 13:42 UTC, pkuGenuine commented on yp_library/utils.py
> +        returned=False, due_time=cr_time - timedelta(days=days)
应该筛选一个时间段而不是一个时间点。不然一小时调用一次肯定会错过。
建议精确到小时就可以

2022-08-12 13:43 UTC, pkuGenuine requested changes
本地多测试一下

2022-08-12 14:30 UTC, pkuGenuine commented on yp_library/utils.py
> +    cr_time = datetime.now
now()

2022-08-12 14:30 UTC, pkuGenuine commented on yp_library/utils.py
> +        due_time__gt=cr_time - timedelta(days=days),
是不是反了......

2022-08-19 16:17 UTC, pkuGenuine commented on yp_library/utils.py
> +    cr_time = datetime.now()
时间精确到小时吧

2022-08-19 16:18 UTC, pkuGenuine commented on yp_library/utils.py
> +    senders = list(Organization.objects.filter(oname="何善衡图书室"))
可以直接用 objects.get

2022-08-19 16:20 UTC, pkuGenuine commented on yp_library/utils.py
> +    receivers = []
可以写成列表生成式

2022-08-19 16:21 UTC, pkuGenuine commented on yp_library/utils.py
> +            violate_stu = Participant.objects.get(Sid=receiver)
不需要考虑是否 > 0，都进行扣分。
使用 update 语句修改数据库

2022-08-20 06:52 UTC, pkuGenuine commented on yp_library/utils.py
> -from django.http import QueryDict, HttpRequest
为什么会引入 http response 呢

2022-08-20 06:54 UTC, pkuGenuine commented on yp_library/utils.py
> +    cr_time = datetime.now()
把 cr_time 精确到小时，可以避免一些边界情况

2022-08-20 06:55 UTC, vassagoP commented on yp_library/utils.py
> -from django.http import QueryDict, HttpRequest
之前调试的时候是通过设置一个url访问来调用函数的，忘记删了

2022-08-20 07:28 UTC, pkuGenuine commented on yp_library/utils.py
> +    cr_time = datetime.now().strftime("%Y-%m-%d %H")
replace(minute=0, second=0, microsecond=0)

2022-08-20 15:02 UTC, pkuGenuine approved these changes

2022-08-20 15:04 UTC, merged