点击申诉自动跳转到修改/查看反馈界面
Yuanpei-Intelligence/YPPF pull request #603
Opened 2022-08-09 06:48 UTC by SouthwestWindQ

地下室违约申诉：违约记录点击预约记录/信用分界面的“申诉”按钮后均自动跳转到反馈界面。后端进行检查，如果该预约记录存在对应的feedback，则跳转到修改feedback/查看feedback的URL中；如不然，则跳转到填写feedback的URL中，并自动选好反馈类型，填写好反馈内容。

书房借阅申诉：书房借阅信息界面中的未申诉记录，点击申诉后跳转到填写feedback/修改feedback草稿的URL中。一旦书房借阅申诉被提交，借阅记录状态将变更为“申诉中”。“申诉中”的记录可以查看feedback详情。

测试无问题。

一些示意图：

未申诉且未填写feedback的地下室违约记录，点击“申诉”后进入如图所示的页面。

![10051660027556_ pic](https://user-images.githubusercontent.com/95567950/183582621-fc742b8b-17cd-4245-810e-53249dd81722.jpg)

已申诉的地下室违约记录，点击“申诉”后进入如图所示的页面。

![10061660027586_ pic](https://user-images.githubusercontent.com/95567950/183582698-13c5f3e7-4257-4088-a0f1-ab037eb71452.jpg)

书房借阅记录界面如图。“申诉中”的记录可以点击“查看申诉”进入填写好的feedback界面（类似上图）

![10071660027709_ pic](https://user-images.githubusercontent.com/95567950/183582941-ac5efa4b-aab6-4a06-82c3-a630ca18a8c7.jpg)

2022-08-09 13:55 UTC, panhongtao07 requested changes
先给点建议

2022-08-09 13:55 UTC, panhongtao07 commented on app/feedback_views.py
> +            feedback_type = request.session['feedback_type']
保留GET的获取方式，在feedback视图可以尝试has_key()，然后跳转GET参数

2022-08-09 13:55 UTC, panhongtao07 commented on app/feedback_views.py
> +            feedback_type = request.session['feedback_type']
保留GET的获取方式，在feedback视图可以尝试has_key()，然后跳转GET参数

2022-08-09 13:55 UTC, panhongtao07 commented on app/feedback_utils.py
> +                LendRecord.objects.filter(id=record_id).update(
模型高度关联是不太好的，尝试找些其他实现方法

2022-08-09 13:55 UTC, panhongtao07 commented on app/feedback_utils.py
> +                request.session.pop('feedback_url')
这些部分我进行了修改

2022-08-09 13:57 UTC, panhongtao07 requested changes
先给点建议

2022-08-09 15:16 UTC, SouthwestWindQ commented on app/feedback_utils.py
> +                LendRecord.objects.filter(id=record_id).update(
根据建议，目前未申诉的记录只要点击申诉则状态就变更为“申诉中”

2022-08-10 13:28 UTC, panhongtao07 approved these changes

2022-08-10 13:29 UTC, merged