搜索结果前端显示，已嵌入搜索框
Yuanpei-Intelligence/YPPF pull request #604
Opened 2022-08-09 15:24 UTC by lingbei-meng

搜索结果前端显示，已嵌入搜索框

2022-08-09 15:25 UTC, lingbei-meng commented
界面展示
![屏幕截图 2022-08-09 232244](https://user-images.githubusercontent.com/95386422/183690759-1e5bc55c-f2c4-4a81-9964-d9e838ee492c.png)

2022-08-10 02:33 UTC, SouthwestWindQ requested changes
有一个总体上的建议：搜索结果（不含搜索框）那一块区域，加一个下面有一条蓝线的“搜索结果”，类似于下面这个框起来的部分：

![image](https://user-images.githubusercontent.com/95567950/183797548-aaa29de7-a987-4436-8a8c-08fc52f1a188.png)

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                        {% if frontend_dict.search_results_list.length != 0 %}
（1）`frontend_dict.`删去，下同
（2）注意是`search_results_list|length`，不是`search_results_list.length`
（3）表格上面加一个`<br/>`吧，比较好看一些

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                              placeholder="搜索书名/作者/索书号/出版社" name="BookName">
这个搜索框是有问题的，以下几个地方需要改一下：
（1）form标签：action="/yplibrary/search/"，method="POST"
（2）input标签：id="keywords"，name="keywords"
以及welcome.html的那个搜索框也麻烦你改一下吧~

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                                <td> {{not_found_message}}</td>
not_found_message你会发现后端并没有准备，所以如果没有检索到结果是不会显示文字的。这边直接写一句话就可以了，并且这边不要用表格形式呈现，用一句灰色的居中的文字来呈现。
以及你好像没有实现在搜索框和搜索结果中间呈现一句“共查询到X条馆藏结果”之类的话，我建议你把这个实现一下，然后在那边if一下，如果length!=0就呈现“共查询到X条馆藏结果”，如果length==0就呈现“没有搜索到馆藏结果”或者其他的你认为更合适的话。这边就不需要再else了，直接不显示结果表格就行。

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                                <th class="text-center">可借阅</th>
改为是否可借阅

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                                    {% endif %}
感觉这个勾和叉不是很好看，可以仿照admin那边的勾和叉吗？就像下面这样：

![image](https://user-images.githubusercontent.com/95567950/183795643-c2442538-7c95-4735-a8a5-69792e0c74f5.png)

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                                <td style="min-width: 80px;"> {{book.title}} </td>
书名加粗一下

2022-08-10 02:33 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +
这边，也就是`<div id="content" class="main-content">`和`<div class="container">`之间，加上下面的代码，注意缩进：
```html
{% if warn_code == 1 %}
<div class="alert alert-warning text-center">{{warn_message}}</div>
{% elif warn_code == 2 %}
<div class="alert alert-success text-center">{{warn_message}}</div>
{% endif %}
```

2022-08-10 07:32 UTC, SouthwestWindQ commented
还有一个点，搜索界面的搜索框同样要支持按照是否借阅查询结果，需要复用一下welcome界面的那个“可借阅”。
有一个welcome.html的地方也麻烦你修改一下~ 就是“可借阅”那边现在是这样的：
```html
<div class="form-check mb-2 mr-sm-2">
    <input class="form-check-input" type="checkbox" id="CanBorrow" name="CanBorrow">
        <label class="form-check-label" for="CanBorrow" style="font-size: 0.9rem;">
            可借阅
        </label>
</div>
```
把里面的`CanBorrow`全部改为`returned`，你在复用的时候也注意一下。

2022-08-15 06:29 UTC, lingbei-meng commented
![截图](https://user-images.githubusercontent.com/95386422/184587058-e5cb17fb-b538-4280-ba2a-383cd39f298e.png)
修改后界面样式

2022-08-15 06:49 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle-fill" viewBox="0 0 16 16">
这里svg加一个style的属性设置颜色，比如`style="color: green;"`，感觉这个green不是很好看，你可以网上搜索一下亮绿色对应的RGB值然后直接设置对应的RGB。下面的叉也是类似地设置一个红色的颜色。

2022-08-15 06:49 UTC, SouthwestWindQ commented on templates/yp_library/search.html
> +                                        <div style="text-align:left;font-size:16px;">共搜索到{{search_results_list|length}}条结果</div>
下面加一个`<br/>`不然显得很挤

2022-08-15 07:00 UTC, SouthwestWindQ approved these changes

2022-08-15 12:50 UTC, pkuGenuine approved these changes

2022-08-15 12:50 UTC, merged