增加元气值获取方式
Yuanpei-Intelligence/YPPF pull request #669
Opened 2022-09-04 16:17 UTC by liangrrr

1. 活动结束时，增加活动小时数 * 10，上取整
2. 每日签到，增加元气值 1 点
3. 反馈被解决并公开，增加元气值 x 点

2022-09-05 01:57 UTC, pkuGenuine commented on generic/models.py
> +            return user
这里为什么要改呢

2022-09-05 01:59 UTC, pkuGenuine commented on generic/models.py
> +        #    user.credit = update_user.credit
类似的也改一下吧，user.YQpoint = update_user.YQpoint

2022-09-05 02:00 UTC, pkuGenuine commented on templates/stuinfo.html
> +                                        {{ context.person.person_id.YQpoint }}元气值
这里直接删掉吧

2022-09-05 02:07 UTC, pkuGenuine commented on app/activity_utils.py
> +                                             YQPointRecord.SourceType.ACTIVITY)
首先不需要使用 UserManager()，用 User.objects 就可以
然后能不能写一个批量修改的函数呀，比如 bulk_modify_YQPoint

2022-09-05 02:15 UTC, pkuGenuine commented on app/activity_utils.py
>      try:
activity_point_per_hour 和 activity_point 也放到 constant 里面吧，名称改一下
activity_point_invalid_titles 和 activity_point_invalid_hour 不需要了

2022-09-05 02:28 UTC, pkuGenuine commented on local_json_template.json
>          "activity_point_invalid_titles": [
这些都删掉吧，下面那个 feedback 也删掉

2022-09-05 02:31 UTC, pkuGenuine requested changes
local_json 尽量不用了，都放到 constant 里面吧
然后看看能不能写一个批量修改元气值的方法

2022-09-05 02:46 UTC, liangrrr commented on generic/models.py
> +            return user
不改的话会有奇怪的报错，感觉原来这么写没什么必要

2022-09-05 15:52 UTC, pkuGenuine commented on generic/models.py
> +            return user
什么报错呢？原来的写法保证返回的时候一定上锁了

2022-09-05 15:55 UTC, pkuGenuine commented on generic/models.py
> +    def bulk_modify_YQPoint(self, user_set: QuerySet['User'], delta: int,
需要加 @transaction.atomic
改一下吧，这里可以只支持批量加，如果要支持批量减的话还需要 check
就叫 bulk_increase_YQPoint
然后加一个 transaction

2022-09-06 16:15 UTC, liangrrr commented on generic/models.py
> +            return user
报错应该是因为实例化UserManager导致的，已将其改回

2022-09-06 16:15 UTC, liangrrr commented on generic/models.py
> +    def bulk_modify_YQPoint(self, user_set: QuerySet['User'], delta: int,
已修改

2022-09-07 00:49 UTC, pkuGenuine approved these changes

2022-09-07 00:49 UTC, merged