将函数视图转为类视图
Yuanpei-Intelligence/YPPF pull request #718
Opened 2023-01-12 10:01 UTC by Aubrey-Liu

- 修改index页面

2023-01-12 10:03 UTC, Aubrey-Liu commented
暂时只是草稿，完成后再覆盖原有的index

2023-01-12 14:29 UTC, pkuGenuine commented on app/views.py
> +
这种基类放到 utils 里面吧

2023-01-12 14:32 UTC, pkuGenuine commented on app/views.py
> +
包括 log.py 里面的东西，也应该放到 utils 里面比较好。以及我新改了 log，可以之后一起改

2023-01-12 14:35 UTC, pkuGenuine commented on app/views.py
> +class IndexView(SecureView):
有没有可能用 TemplateView 呢

2023-01-12 14:42 UTC, pkuGenuine commented on app/views.py
> +    def param_check(
有没有可能先做 check param 再进 dispatch？

2023-01-12 15:11 UTC, Aubrey-Liu commented on app/views.py
> +class IndexView(SecureView):
没看出templateview有什么优势，所以就用的最基础的

2023-01-12 15:13 UTC, Aubrey-Liu commented on app/views.py
> +    def param_check(
我觉得可行，好处就是省去重复代码了，我试试吧

2023-01-12 15:15 UTC, Aubrey-Liu commented on app/views.py
> +
这个没问题

2023-01-13 03:25 UTC, pkuGenuine commented on utils/views.py
> +    ) -> Union[None, HttpResponse, HttpResponseRedirect]:
类型标注可以改成 `'None | HttpResponse | HttpResponseRedirect'`

2023-01-13 03:26 UTC, pkuGenuine commented on utils/views.py
> +from app.log import except_captured
app.log 肯定是要废弃掉的

2023-01-13 03:27 UTC, Aubrey-Liu commented on utils/views.py
> +    ) -> Union[None, HttpResponse, HttpResponseRedirect]:
ok

2023-01-13 03:27 UTC, Aubrey-Liu commented on utils/views.py
> +from app.log import except_captured
那等废弃的时候统一改吧

2023-01-13 03:56 UTC, pkuGenuine requested changes

2023-01-13 03:56 UTC, pkuGenuine commented on utils/views.py
> +        return wrapped_dispatch(request, args, kwargs)
这一块看起来很复杂，，，我觉得既然用类进行包装了，就没必要再用装饰器了，不如直接显示的写出来。然后 login_required 可以改成 perm_check，作为一个类方法，暂时可以只检查登录，但是可以被覆盖。

2023-01-13 03:56 UTC, pkuGenuine commented on utils/views.py
> +from app.log import except_captured
先改成显示的 `try` 吧，具体的后面再说

2023-01-13 03:56 UTC, pkuGenuine commented on app/views.py
> +class IndexView(SecureView):
原版的 TemplateView 只在 get 里进行了 render 确实没啥用。能不能把这套也搞到 post 里？
我有个貌似还行的思路，你看看靠谱不：
Param 分成 `get_param` 和 `post_param`，不然还得在 client 处判断 http 方法
加上 `get_context` 和 `post_context`
然后在 `dispatch` 里的调用链如下：
`perm_check` (保证不能出错)
`get_param` or `post_param`
`get_context` or `post_context`
`render`

2023-01-15 08:23 UTC, pkuGenuine commented on utils/views.py
> +from .log import err_capture
引入顺序反了，先第三方库，然后才是本地

2023-01-15 08:32 UTC, Aubrey-Liu commented on utils/views.py
> +from .log import err_capture
ok

2023-01-15 08:56 UTC, pkuGenuine commented on utils/views.py
> +    response_class = TemplateResponse
加一下类型标注吧

2023-01-15 09:05 UTC, pkuGenuine reviewed
还有两个问题吧：

1. 我觉得有问题的输入和非预期的错误应该分开对待，目前至少把 log 分开吧。非预期的错误捕获主要是为了 debug；有问题的输入是看谁在打咱们。
2. handler 如果正常渲染的话返回 none，但是设置 extra_context，在 dispatch 中进行 render 感觉好一点？

2023-01-15 14:29 UTC, pkuGenuine approved these changes

2023-01-15 14:29 UTC, merged