修改Config的实现
Yuanpei-Intelligence/YPPF pull request #723
Opened 2023-01-13 09:06 UTC by sunyb-dot

还不能merge，先发上来看看这个思路是不是合适~
## 现在的依赖关系和结构：
utils/config.py依赖boot，剩下的应用依赖utils/config.py
每个app下的config.py从utils/config.py读取本app要用的config
目前根据local_json_template.json生成utils/config.py，这个可以考虑以后加一个命令python manage.py generate_config类似的；修改local_json中的项需要重新生成
各个app的实现估计差距会很大

## 目前的问题：
修改了local_json_template.json，需要大家修改

## 还没做的事情：
把app里众多的get_setting用上述方法替代

2023-01-13 23:57 UTC, sunyb-dot commented
现在也从local_json_template.json中读入默认设置，移除了部分手动给出默认设置的值

2023-01-15 00:53 UTC, pkuGenuine commented on boot/config.py
> +from utils.config import *
这没有循环导入的问题嘛 2333

2023-01-15 00:55 UTC, pkuGenuine commented on boot/config.py
> +        self.scheduler_log: str = Setting("YPPF_SCHEDULER_LOG_FILE",
这个 scheduler_log 可以删掉了

2023-01-15 00:55 UTC, pkuGenuine commented on boot/config.py
> +        self.log_debug: str = Setting("YPPF_LOG_DEBUG", default="")
这个直接改成 log_level 吧

2023-01-15 00:59 UTC, pkuGenuine commented on utils/config.py
> +            if type(object.__getattribute__(self, __name)) is Setting:
用 `isinstance` 更直接一点吧？

2023-01-15 01:13 UTC, pkuGenuine commented on utils/config.py
> +    trans_func: callable
类型标注不太对，`Callable`，从 typing 里导入

2023-01-15 01:15 UTC, pkuGenuine commented on utils/config.py
> +    trans_func: callable
`Callable[[str], Any]`

2023-01-15 01:19 UTC, pkuGenuine commented on utils/config.py
> +        self.trans_func = trans_func if trans_func is not None else lambda x: x
感觉如果 `trans_func` 是 `None` 就不操作更好一点
然后下面可以改成 
`
if self.value is None:
    self.value = os.getenv(self.path) or base_get_setting(...
    if self.trans_func is not None:
        self.value = self.trans_func(
`

2023-01-15 01:23 UTC, pkuGenuine commented on utils/config.py
> +        self.trans_func = trans_func if trans_func is not None else lambda x: x
好像不太行，不然得改 base_get_setting。
不过其实 base_get_setting 的大部分功能确实没啥用了

2023-01-15 01:26 UTC, pkuGenuine commented on utils/config.py
> +                print(f"{e}, returning {default} instead")
把 `debug` 这里的逻辑先去掉吧，这样就不依赖 django 的启动了

2023-01-15 01:37 UTC, pkuGenuine requested changes
大框架我觉得没问题，后续应该是要把 base_get_setting 改掉的。
可以先把 query_setting 拿出来按照新代码的需要修改，然后 base_get_setting 仅作为暂时兼容使用，新代码中避免使用

2023-01-15 08:53 UTC, pkuGenuine approved these changes

2023-01-15 08:53 UTC, merged