first appointmeng config try
Yuanpei-Intelligence/YPPF pull request #730
Opened 2023-01-31 12:09 UTC by Ning020510

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +        if DEBUG: print('Loading token field...')
这两个print可以去掉

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +        self.semester_start = LazySetting("semester_data/semester_start", str_to_time)
第二个参数去掉

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +GLOBAL_CONF = AppointmentConfig()
变量名写CONFIG吧

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +GLOBAL_CONF = AppointmentConfig()
然后结尾要有一个空行

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +            self.debug_stuids = []
直接写self.debug_studis = []吧，这个暂时没啥用先不管

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +    def __init__(self, dict_prefix: str = 'appointment'):
prefix用underground吧

2023-01-31 12:33 UTC, Aubrey-Liu commented on Appointment/config.py
> +    def __init__(self, dict_prefix: str = 'appointment'):
说不定要改应用名字

2023-01-31 14:59 UTC, pkuGenuine requested changes

2023-01-31 14:59 UTC, pkuGenuine commented on Appointment/config.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
不需要

2023-01-31 14:59 UTC, pkuGenuine commented on Appointment/config.py
> +from Appointment import str_to_time
引入规范，逗号后加空格，优先引入标准库，然后再是本地文件
~~~
import os

from boot. ...
~~~

不要再从 boot 直接引入 UNDERGROUND_URL, WECHAT_URL，通过 config 方式进行读取

2023-01-31 14:59 UTC, pkuGenuine commented on config_template.json
> +            "wechat":""
hash 放到最外层 wechat 处，system_log 不再需要，semester 信息放在 global 内

2023-01-31 14:59 UTC, pkuGenuine commented on Appointment/config.py
> +        self.debug_stuids = []
先删掉，相关内容可以注释掉

2023-01-31 14:59 UTC, pkuGenuine commented on Appointment/config.py
> +        self.account_auth = True
这个应该也可以删掉，全局没有搜到使用

2023-01-31 15:02 UTC, Ning020510 commented on Appointment/config.py
> +BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
好的！

2023-01-31 15:12 UTC, Ning020510 commented on Appointment/config.py
> +from Appointment import str_to_time
请问如何通过 config 进行读取呢？这部分代码还不是很熟悉 qwq

2023-01-31 15:22 UTC, Ning020510 commented on Appointment/config.py
> +from Appointment import str_to_time
好的！

2023-01-31 15:28 UTC, Ning020510 commented on config_template.json
> +            "wechat":""
config.py 文件中有一行

self.system_log = LazySetting('system_log')

也一起删掉嘛

2023-02-01 04:52 UTC, panhongtao07 requested changes
问题很大，改完地下室代码基本不用跑了，虽然修复起来不难。pr请先保证测试通过！

2023-02-01 04:52 UTC, panhongtao07 commented on config_template.json
> -        "semester": "Spring"
整个文件对比视图不可读，请最小化修改范围，这个修改错误很大

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/config.py
> +        self.wechat_salt = LazySetting('hash/wechat')
这些设置并不在地下室中，考虑prefix，他们有些需要从对应应用的config读

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/config.py
> +class AppointmentConfig(Config):
这个类在哪里被导入了呢？哪里都没有，起码通过自动测试ok？

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/config.py
> +            self.debug_stuids = []
错误的，有用，地下室的debug消息都用这个 @Aubrey-Liu

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/config.py
> +        self.debug_stuids = []
？？

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/utils/utils.py
>                  start_time=datetime.now(),
这不是用到了吗，为什么删掉？

2023-02-01 04:52 UTC, panhongtao07 commented on boot/config.py
错误的config位置，由对应应用维护

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/__init__.py
>          self.account_auth = True
确实可以删除

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/__init__.py
> -            self.debug_stuids = []
请恢复

2023-02-01 04:52 UTC, panhongtao07 commented on Appointment/models.py
> +                appoint__Astart__gt=CONFIG.semester_start,
这个文件中没有引入GLOBAL_INFO或者CONFIG的任何一个，联系 @pkuGenuine 解决，代码报错

2023-02-01 08:49 UTC, pkuGenuine commented on Appointment/config.py
> +            self.debug_stuids = []
debug_stuids 可以放在 "wechat" 下

2023-02-01 08:50 UTC, pkuGenuine commented on Appointment/__init__.py
> -            self.debug_stuids = []
这里删掉没问题的，用的地方从 app 的 Config 中读取

2023-02-01 08:52 UTC, pkuGenuine commented on Appointment/config.py
> +from Appointment import str_to_time
不同的引入关系之间加一行空行，可以参考一下[代码规范](https://epu4t4i0lr.feishu.cn/wiki/wikcnfScIUQsdFsEBgbVwfpqYqc)

2023-02-01 08:55 UTC, pkuGenuine commented on Appointment/config.py
> +        self.wechat_salt = LazySetting('hash/wechat')
除了 this_url，其他不需要在这里写。如果有用到的地方从相应的地方读入。
比如有地方用到 wechat_salt，则应该从 app.config 中引入 `ProfileConfig`，使用 `ProfileConfig.hash_wechat`

2023-02-01 16:01 UTC, panhongtao07 commented on Appointment/__init__.py
> -            self.debug_stuids = []
这里没必要删掉啊，这个pr里没必要涉及这个

2023-02-01 16:02 UTC, panhongtao07 commented on Appointment/__init__.py
> -            self.debug_stuids = []
我是觉得让这个pr复杂化了，何况如果不使用GLOBAL_INFO，自然以后会删，这个文件的这个类相当于保留了曾经的地下室配置信息

2023-02-03 13:35 UTC, pkuGenuine commented on Appointment/config.py
> +APP_NAME = apps.get_app_config('Appointment').name
直接 `AppConfig.name` 不好吗？

2023-02-03 13:37 UTC, pkuGenuine commented on Appointment/config.py
> +        self.this_url = LazySetting('underground/base_url')         # 地下室的访问入口
多了个前缀？

2023-02-03 13:38 UTC, pkuGenuine commented on Appointment/config.py
> +from . import str_to_time
能不能直接用 datetime 呀，或者放到最外层的 utils 里面去

2023-02-03 13:42 UTC, pkuGenuine commented on Appointment/utils/identity.py
>  from functools import wraps
functools 移上去

2023-02-03 13:43 UTC, pkuGenuine commented on Appointment/utils/identity.py
> +from app import API
没用到、？

2023-02-03 14:02 UTC, Aubrey-Liu commented on Appointment/utils/identity.py
> +from app import API
啥没用到？都有用到啊

2023-02-03 14:02 UTC, Aubrey-Liu commented on Appointment/config.py
> +        self.this_url = LazySetting('underground/base_url')         # 地下室的访问入口
确实

2023-02-05 14:40 UTC, panhongtao07 approved these changes
修改后应该可用了

2023-02-08 14:54 UTC, merged