add some fake data
Yuanpei-Intelligence/YPPF pull request #733
Opened 2023-02-08 12:06 UTC by sanshisan24

2023-02-08 15:49 UTC, pkuGenuine commented on dm/management/fake_records.py
> -    sid = username = "2000000000"
这个为啥要改呢 2333

2023-02-08 15:51 UTC, pkuGenuine commented on dm/management/fake_records.py
> -    sid = username = "2000000000"
然后多次重复用到硬编码建议提到顶部作为常量

2023-02-08 15:53 UTC, pkuGenuine commented on dm/management/fake_records.py
> +
为啥多了一行

2023-02-08 15:56 UTC, pkuGenuine commented on dm/management/fake_records.py
> +    biography = '为按死的鸟发哪家低年级你杀菌灯假设的静安寺的静安寺大石街道'
如果 model 里的 field 有 default 值就可以不加，有 null=True 可能也行？

2023-02-08 15:58 UTC, pkuGenuine commented on dm/management/fake_records.py
> +    NaturalPerson.objects.all().delete()
单独再写一个 command，用来删除所有的数据比较好？

2023-02-09 02:50 UTC, sanshisan24 commented on dm/management/fake_records.py
> -    sid = username = "2000000000"
改回去了

2023-02-09 02:51 UTC, sanshisan24 commented on dm/management/fake_records.py
> +
改了

2023-02-09 02:52 UTC, sanshisan24 commented on dm/management/fake_records.py
> +    biography = '为按死的鸟发哪家低年级你杀菌灯假设的静安寺的静安寺大石街道'
考虑测试需要，有的default给设值了，如果不需要我删掉

2023-02-09 02:52 UTC, sanshisan24 commented on dm/management/fake_records.py
> +    NaturalPerson.objects.all().delete()
刚看到已经有删除数据库的命令了，相关的删除命令我会删掉

2023-02-09 12:36 UTC, pkuGenuine commented on dm/management/fake_records.py
> +    biography = '各位考官好，今天能够站在这里参加面试，有机会向各位考官请教和学习，' \
你改这个干啥，，，

2023-02-09 12:37 UTC, pkuGenuine commented on dm/management/fake_records.py
> -
在第三方库和本地包直接有一个空行是合理的，，，

2023-02-09 13:14 UTC, pkuGenuine requested changes
再多加几个用户吧，自然人包括老师，不然有些功能还是没法访问

2023-03-02 04:16 UTC, sanshisan24 commented on dm/management/fake_records.py
> +    biography = '各位考官好，今天能够站在这里参加面试，有机会向各位考官请教和学习，' \
随便改改**

2023-03-02 05:14 UTC, pkuGenuine commented on dm/management/fake_records.py
> +    Position.objects.all().delete()
应该只需要删 User, OrgType, OrgTag 就行了

2023-03-02 05:15 UTC, pkuGenuine commented on dm/management/fake_records.py
> +TEACHER_NAME = "1800017710"
可以简单点，方便测试，以及不要把个人信息放上来呀

2023-03-02 05:18 UTC, pkuGenuine commented on dm/management/fake_records.py
>  assert settings.DEBUG, 'Should not import fake_records in production env.'
改成 boot.config.DEBUG 吧，然后这个 settings 应该也不用引入了

2023-03-15 13:29 UTC, pkuGenuine approved these changes

2023-03-15 13:29 UTC, merged