Develop
Yuanpei-Intelligence/YPPF pull request #736
Opened 2023-02-08 15:42 UTC by vassagoP

修改依赖

2023-02-08 16:03 UTC, pkuGenuine commented on env/docker-compose.yml
> +  yppf-mysql-config:
注意不要引入没必要的改动，，，

2023-02-08 16:05 UTC, pkuGenuine commented on app/config.py
> +class CourseElection:
这样是有一点不优雅，，，直接改成 `CourseConfig` 吧，然后也继承 `Config`，用 `LazySetting` 作为 fields。

2023-02-08 16:11 UTC, pkuGenuine commented on app/course_views.py
> +from app.config import CONFIG as APP_CONFIG
app/views_dependency.py 里应该导入过这个东西了？不需要重复引入

2023-02-09 08:18 UTC, vassagoP commented on app/course_views.py
> +from app.config import CONFIG as APP_CONFIG
去掉这一行会报未定义

2023-02-09 08:25 UTC, vassagoP commented on env/docker-compose.yml
> +  yppf-mysql-config:
这里好怪，看上去已经没区别了但还是显示了改动是为啥

2023-02-09 13:00 UTC, pkuGenuine commented on env/docker-compose.yml
> +  yppf-mysql-config:
空行的区别

2023-02-09 13:11 UTC, pkuGenuine commented on app/course_views.py
> +from app.config import CONFIG as APP_CONFIG
在 app/views_dependency.py 中导入过 CONFIG，
可以把用到的 APP_CONFIG 改为 CONFIG

2023-02-09 13:12 UTC, pkuGenuine requested changes
Merge 一下吧，不然有些改动看不出来了

2023-02-09 15:13 UTC, pkuGenuine approved these changes

2023-02-09 15:13 UTC, panhongtao07 approved these changes
ok

2023-02-09 15:13 UTC, merged