问卷系统搭建初步
Yuanpei-Intelligence/YPPF pull request #754
Opened 2023-07-29 14:25 UTC by zrbpkuyp

能够在系统中正常显示

2023-07-29 15:57 UTC, pkuGenuine commented on questionnaire/views.py
> +from django.shortcuts import render, get_object_or_404, redirect
应该是有一些引用没有用到，在 dev container 里应该能看到，是暗色的

2023-07-29 15:57 UTC, pkuGenuine commented on questionnaire/views.py
> +def index(request):
删掉无关代码

2023-08-05 13:07 UTC, panhongtao07 requested changes
没看views实现逻辑，揪了一些细节

2023-08-05 13:07 UTC, panhongtao07 commented on questionnaire/views.py
> +    queryset = Survey.objects.all()
所有提供了get_queryset方法的类都应该删除queryset属性。

2023-08-05 13:07 UTC, panhongtao07 commented on questionnaire/views.py
> +        raise PermissionError
文件末空行

2023-08-05 13:07 UTC, panhongtao07 commented on questionnaire/views.py
> +            return Survey.objects.filter(status=Survey.Status.PUBLISHED, start_time__lte=timezone.now(), end_time__gte=timezone.now())
为什么使用timezone而不是datetime？和其他代码统一吧

2023-08-05 13:07 UTC, panhongtao07 commented on questionnaire/views.py
> +from questionnaire.permissions import *
所有`import *`的文件都必须**明确显式**写出__all__文件的所有导出内容，要么就别`import *`！

2023-08-05 13:07 UTC, panhongtao07 commented on questionnaire/models.py
models文件最好定义__all__

2023-08-07 06:49 UTC, pkuGenuine commented on questionnaire/models.py
> +    status = models.SmallIntegerField("问卷状态", choices=Status.choices, default=Status.DRAFT)
填写时间改成最后修改时间吧，然后 auto save

2023-08-07 06:51 UTC, pkuGenuine commented on questionnaire/permissions.py
> +    return request.user.is_staff or request.user == owner or request.user == asker
is_staff 删掉吧，可以使用 admin site。

2023-08-07 06:53 UTC, pkuGenuine commented on questionnaire/permissions.py
> +
空行，此外可以加一下类型注释

2023-08-07 07:27 UTC, pkuGenuine commented on questionnaire/views.py
> +from django.utils import timezone
这个 import 应该移到上面去

2023-08-07 07:28 UTC, pkuGenuine commented on questionnaire/views.py
> +        # 每次访问时自动更新问卷状态, 问卷过期自动设置为FINISHED # TODO: 有没有更好的自动更改机制？
定时任务

2023-08-07 07:29 UTC, pkuGenuine commented on questionnaire/views.py
> +        if self.request.user.is_staff:
staff 不需要特权

2023-08-09 15:28 UTC, closed without merging