assign dormitory
Yuanpei-Intelligence/YPPF pull request #766
Opened 2023-08-12 13:44 UTC by asuka-su

2023-08-13 10:00 UTC, qingzhenduyu commented
commit 太多了，git rebase一下吧，然后把最新的算法也更新一下？

2023-08-13 15:47 UTC, qingzhenduyu requested changes

2023-08-13 15:47 UTC, qingzhenduyu commented on dormitory/management/commands/assign_dormitory.py
> +        if len(set(origin)) < len(self.stu) - 1:
类似这些设置匹配规则的地方都建议添加注释，不然一年之后大家都看不懂是在做啥了哈哈哈

2023-08-13 15:47 UTC, qingzhenduyu commented on dormitory/management/commands/assign_dormitory.py
> +            if stu.data['gender'] == "男":
有个小问题，如果实际情况会有2个地域相同的人住在同一个宿舍，这里的check_must会不会导致陷入死循环？不知道我这里理解的对不对？

2023-08-14 13:53 UTC, asuka-su commented on dormitory/management/commands/assign_dormitory.py
> +            if stu.data['gender'] == "男":
确实会（

2023-08-26 07:11 UTC, closed without merging