元气满满 成就更新函数
Yuanpei-Intelligence/YPPF pull request #778
Opened 2023-08-28 16:04 UTC by zrbpkuyp

初始版本 尚未测试 感觉时间上也不太好再优化

2023-08-29 04:57 UTC, pkuGenuine commented on app/YQPoint_utils.py
> +        if not unlocked_achievements.filter(achievement__name='首次获得元气值'):
可以用 get_or_create 进行修改？

2023-09-01 10:17 UTC, pkuGenuine commented on app/views.py
> +    semester_start = datetime(2023, 8, 19, 0, 0, 0)
接口可以改了

2023-09-01 10:17 UTC, pkuGenuine commented on app/YQPoint_utils.py
> +        if income >= 10:
能不能稍微函数化一点？

2023-09-01 10:18 UTC, pkuGenuine commented on app/YQPoint_utils.py
> +                user_display.append('解锁成就，元气满满——学期内获得10元气值!')
尝试调用解锁成就的接口？

2023-09-01 10:19 UTC, pkuGenuine commented on app/YQPoint_utils.py
> +                user_display.append('解锁成就，元气满满——学期内获得10元气值!')
然后获取元气值的数量应该要存到 Achievement 里面

2023-09-02 12:03 UTC, zrbpkuyp commented
进行了大刀阔斧的重写

2023-09-03 08:52 UTC, panhongtao07 requested changes
仍需修改，我将修改部分注释

2023-09-03 08:52 UTC, panhongtao07 commented on app/academic_utils.py
> +from achievement.api import trigger_achievement
都没用到，删了吧

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +                user, Achievement.objects.get(name=achievement_name))
用列表写，`dict`语义不保序，`for day_bound, achievement_name in ACHIEVEMENT_INFOS`，另外常量要大写

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +
全都用列表写，不需要索引为什么用dict？

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +from typing import Tuple
Tuple改用tuple，不要impoort

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +from achievement.api import trigger_achievement, bulk_add_achievement_record
没用的建议删掉

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/api.py
> +    ])
依赖于unique，需要注释

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/api.py
> +    )
原子性依赖于unique，需要注释

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/api.py
这是自动导入吗，好像没用到，删了吧

2023-09-03 08:52 UTC, panhongtao07 commented on app/YQPoint_utils.py
> +def get_income_expenditure(user: User, start_time: datetime, end_time: datetime) -> Tuple[int, int, bool]:
添加到__all__

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +def get_income_expenditure(user: User, start_time: datetime, end_time: datetime) -> Tuple[int, int, bool]:
不要复写代码，在函数中import，删除本文件中的函数。

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +def unlock_YQMM_series(user: User, start_time: datetime, end_time: datetime) -> None:
类似的命名需要修改，不要使用中文缩写等无法识别的命名，学习项目代码规范

2023-09-03 08:52 UTC, panhongtao07 commented on achievement/unlock_api.py
> +def unlock_ZHSH_signin(user: User, continuous_days: int) -> bool:
需要修改命名

2023-09-04 07:55 UTC, zrbpkuyp commented
修改上述问题

2023-09-05 07:03 UTC, panhongtao07 approved these changes
好像行了

2023-09-05 10:19 UTC, merged