为活动总结修改界面添加修改参与人员的接口
Yuanpei-Intelligence/YPPF pull request #793
Opened 2023-09-16 19:37 UTC by Infinity12306

2023-09-16 19:43 UTC, Infinity12306 commented
<img width="589" alt="image" src="https://github.com/Yuanpei-Intelligence/YPPF/assets/104830779/5616dae3-5eb9-4fed-ba98-11186f65ddcd">
使用"users.update(YQpoint=F('YQpoint') + delta)"会导致Error："django.db.utils.OperationalError: (1093, "You can't specify target table 'generic_user' for update in FROM clause")"，改为等价的for循环则不会出错，尝试了各种方法仍无法解决

2023-09-23 15:22 UTC, Infinity12306 commented
> <img alt="image" width="589" src="https://user-images.githubusercontent.com/104830779/268468309-5616dae3-5eb9-4fed-ba98-11186f65ddcd.png">
> * 使用"users.update(YQpoint=F('YQpoint') + delta)"会导致Error："django.db.utils.OperationalError: (1093, "You can't specify target table 'generic_user' for update in FROM clause")"，改为等价的for循环则不会出错，尝试了各种方法仍无法解决，也不清楚具体出错原因
> * 直接导致错误的代码为activity_views.py中1033-1034行的"User.objects.bulk_increase_YQPoint(to_add_participant_usrs, point, "参加活动", YQPointRecord.SourceType.ACTIVITY)"
> * 完整的html报错文件github不支持上传，可以私发，不过已经非常仔细地研究过，检查了直接导致错误的代码处的local variable，看不出任何问题……

已解决

2023-09-23 15:23 UTC, Infinity12306 commented
> <img alt="image" width="589" src="https://user-images.githubusercontent.com/104830779/268468309-5616dae3-5eb9-4fed-ba98-11186f65ddcd.png">
> * 使用"users.update(YQpoint=F('YQpoint') + delta)"会导致Error："django.db.utils.OperationalError: (1093, "You can't specify target table 'generic_user' for update in FROM clause")"，改为等价的for循环则不会出错，尝试了各种方法仍无法解决，也不清楚具体出错原因
> * 直接导致错误的代码为activity_views.py中1033-1034行的"User.objects.bulk_increase_YQPoint(to_add_participant_usrs, point, "参加活动", YQPointRecord.SourceType.ACTIVITY)"
> * 完整的html报错文件github不支持上传，可以私发，不过已经非常仔细地研究过，检查了直接导致错误的代码处的local variable，看不出任何问题……

已通过queryset转list，强制立刻访问数据库解决

2023-10-06 13:25 UTC, qingzhenduyu commented
@panhongtao07 这个PR可以merge了吗

2023-10-07 04:59 UTC, Infinity12306 commented
刚刚把本地和远程仓库同步的时候pr自动关了，没有做任何改动，重新开启

2023-10-07 12:12 UTC, pkuGenuine commented on app/activity_views.py
> +from typing import Literal, List
没必要加 `List` 吧，直接用 `list` 就可以

2023-10-07 12:13 UTC, pkuGenuine commented on app/activity_views.py
> +    _modify_participants,
既然做导入，为什么要加下换线呢

2023-10-07 12:14 UTC, pkuGenuine commented on app/activity_views.py
> +    user_queryset = User.objects.filter(id__in=user_id_list)
直接写成 value_list?

2023-10-07 12:17 UTC, pkuGenuine commented on app/activity_utils.py
> +    removed_participation.delete()
为啥要做这个逻辑 ？？？

2023-10-07 12:18 UTC, pkuGenuine commented on app/activity_utils.py
> +    removed_participation.delete()
如果元气值不足了呢？就不扣了吧

2023-10-07 12:19 UTC, pkuGenuine commented on app/activity_utils.py
> +def _modify_participants(activity: Activity, now_participant_uids):
我其实建议改成只可以加人，减人不是特别有必要，而且麻烦多了

2023-10-07 12:19 UTC, pkuGenuine submitted a review, later dismissed
Need change

2023-10-07 18:04 UTC, Infinity12306 commented
学长好，我刚刚加了一个新的commit，做了“修改每周活动总结提醒对象范围；每周活动总结入口暂时只为四个官方组织开放”两件事。

- 修改每周活动总结提醒对象为全体组织负责人，因为每周活动总结针对的是没有走系统的活动，我们无从判断需要提醒哪些组织，只能全部提醒负责人检查有无遗漏未申报活动
- 目前每周活动总结无须再审核直接发放元气值，为防止恶意刷元气值，暂时只给“团委，学学学委员会，学学学学会，学生会”四个官方组织开放入口

2023-10-07 18:08 UTC, Infinity12306 commented on app/activity_utils.py
> +    removed_participation.delete()
这个我当时写的时候也在想元气值不够咋办，而且多一个撤销发放的元气值记录也非常奇怪，现在系统的元气值不能扣到负数吗，或者考虑加个定时任务，定期检查元气值够不够扣？

2023-10-07 18:09 UTC, Infinity12306 commented on app/activity_utils.py
> +def _modify_participants(activity: Activity, now_participant_uids):
嗯嗯，我先暂时改成只可以加人吧

2023-10-07 18:25 UTC, Infinity12306 commented
学长之前提的comment，我打算设置成已有的参与人不可删除，具体html里option element支不支持这种操作我睡醒再来看吧x（本来打算11点半睡觉的🥲）

2023-10-07 18:26 UTC, Infinity12306 commented
其他部分我本地改好了，明天把这个改完然后再本地测试一下我就交commit

2023-10-08 06:17 UTC, panhongtao07 requested changes
存在问题，另外仍需解决develop冲突

2023-10-08 06:17 UTC, panhongtao07 commented on app/activity_views.py
>                      context = succeed(
添加功能后代码已经变得复杂，不宜再将new_submit和modify_submit混在一处执行，在`if post_type in ["new_submit", "modify_submit"]:`时就分离吧，像cancel_submit一样

2023-10-08 06:17 UTC, panhongtao07 commented on app/activity_views.py
> +    person_list = NaturalPerson.objects.activated()
此处的范围没有在post时检查

2023-10-08 06:17 UTC, panhongtao07 commented on app/activity_views.py
> +            return redirect(message_url(wrong('您没有权限发起每周活动总结')))
统一

2023-10-08 06:17 UTC, panhongtao07 commented on app/jobs.py
> +        to_notify_user = select_current(incharge_users).first().person.get_user()
应该直接发给这个组织，而不是其管理者，因为微信发送会自动转发给他们

2023-10-08 06:17 UTC, panhongtao07 commented on templates/activity_summary_show.html
>                                      onclick="location.href = '/weekly-activity-summary/';"
href使用reverse tag吧，不要直接写路径了

2023-10-08 06:17 UTC, panhongtao07 commented on templates/modify_activity_summary.html
> +    <link href="{% static 'Appointment/assets/select2/css/select2.min.css' %}" rel="stylesheet" />
css文件路径不对，不应该是地下室的

2023-10-08 06:17 UTC, panhongtao07 commented on templates/modify_activity_summary.html
> +    function matchCustom(params, data) {
使用user搜索函数

2023-10-08 07:29 UTC, Infinity12306 commented on app/activity_utils.py
> +        "person_id__person_id__username", flat=True)
SQ模版具体是指？🥲

2023-10-08 08:39 UTC, Infinity12306 commented on app/activity_utils.py
> +def _modify_participants(activity: Activity, now_participant_uids):
activity_utils.py 里面没有__all__？

2023-10-08 09:07 UTC, Infinity12306 commented on app/activity_utils.py
> +        person_id__username__in=new_participant_uids)
学长是指直接传入id而不是uid，把由uid得到id的过程放在这个函数外吗

2023-10-08 11:09 UTC, Infinity12306 commented on app/activity_views.py
> +    person_list = NaturalPerson.objects.activated()
学长指的检查是person_list的筛选吗，但post里面不需要用到学生信息（即js_stu_list）啊

2023-10-08 17:08 UTC, panhongtao07 reviewed
感觉没完全理解，没事

2023-10-09 05:52 UTC, Infinity12306 commented on templates/activity/summary_application.html
> +                                                data-toggle="tooltip" data-placement="bottom" title='原有参与人员不支持删除，即使通过X号删除下次进入该界面还是会存在哦。'>
allowClear设为false那个X号还是存在，原因未知，要不还是把这个提示给删了？

2023-10-09 13:28 UTC, panhongtao07 approved these changes
ok

2023-10-10 15:35 UTC, panhongtao07 commented on app/activity_utils.py
> +        person_id__username__in=new_participant_uids)
不是，是指需要一步检查合法性

2023-10-10 15:36 UTC, panhongtao07 commented on app/activity_views.py
> +    person_list = NaturalPerson.objects.activated()
post时应该检查表单中所有id都在person_list的范围内，因为他们有可能篡改

2023-10-10 15:39 UTC, merged