通过自定义认证后端实现的权限黑名单
Yuanpei-Intelligence/YPPF pull request #808
Opened 2024-01-19 08:25 UTC by Deophius

在数据库中记录了一个“权限黑名单”（`generic.models.PermissionBlacklist`），其功能类似于`/etc/hosts.deny`，如果某个用户的某条权限在这里有记录，那么即使用户所在的组有这个权限，后端仍然会拒绝授权。

同时为了防止在程序中把权限的名称打错，在非生产环境下（通过`boot.config.DEBUG`判断），后端对于传入的权限名称会进行验证，如果在数据库中不存在对应的权限，那么会抛出`ValueError`进行提示。

这个branch中用这个功能实现了地下室的预约和取消预约两个权限，姑且作为一个简单的demo吧。

在权限黑名单管理页面，可以通过搜索栏检索用户和权限：
<img width="1019" alt="image" src="https://github.com/Yuanpei-Intelligence/YPPF/assets/44802910/ea961b57-a977-4a5b-9598-977f2c7d43bc">

在需要使用权限的地方，写法与使用Django内置权限无异：

```python
@identity_check(redirect_field_name='origin')
def checkout_appoint(request: UserRequest):
    # Other code ...
    if not request.user.has_perm('Appointment.make_appointment'):
        wrong('您没有预约地下室的权限', render_context)
    # Proceed assuming permission granted ...
```

2024-01-21 04:46 UTC, panhongtao07 commented
两处再讨论一下吧
- 我的理解是用户类型的额外权限是另一个backend实现的，不是覆盖当前backend，所以本来的权限系统可能不用黑名单，这个看现在到底需要怎么实现，有没有需求；
- 权限能不能用中文，“防止在程序中把权限的名称打错”的更好方法是用常量。
```python
class Appoint:
    ...
    class Perm(TextChoices):
        ...
    class Meta: permissions=Perm.choices
```

2024-01-22 14:55 UTC, panhongtao07 requested changes
可以使用更好的工具，我已经上传了

2024-01-22 14:55 UTC, panhongtao07 commented on Appointment/models.py
> +            ('取消预约', '取消预约')
说明用中文就可以了，code不用，写法是这样，另外，我觉得“创建预约”比“make”更符合之前的yppf说法
```python
from utils.models.choice import choice

class Permission(BasePermission):
    CREATE = choice('create_appointment', '创建预约')
    CANCEL = choice('cancel_appointment', '取消预约')
```

2024-01-22 14:55 UTC, panhongtao07 commented on Appointment/migrations/0004_alter_appoint_options.py
> +        ),
稍后试试能否自动修改，最后提交一个迁移文件就可以了，前面的可以删掉，不用把中间的修改过程留下来

2024-01-22 15:00 UTC, panhongtao07 commented on Appointment/migrations/0004_alter_appoint_options.py
> +        ),
我的意思是3,4甚至之后的迁移文件，保留一个就行了，最终提交前删掉这几个并重新生成

2024-01-22 15:01 UTC, panhongtao07 commented on generic/backend.py
> +            raise ValueError(f'Unknown permission string "{perm}"')
改好之后这里可以删了

2024-01-22 15:02 UTC, panhongtao07 commented on generic/backend.py
> +        type(self)._check_permission_string(perm)
这个写法不常见，反正后面会删

2024-01-22 15:03 UTC, panhongtao07 commented on generic/backend.py
> +            lambda user: perm not in PermissionBlacklist.get_cancelled_permissions(user),
这代码运行效率有点低，不太好，改一下吧

2024-01-22 15:15 UTC, panhongtao07 requested changes
部分权限处理的效率略低，缺乏可用性

2024-01-22 15:15 UTC, panhongtao07 commented on generic/models.py
> +    @staticmethod
用classmethod

2024-01-22 15:15 UTC, panhongtao07 commented on generic/models.py
空行2行，参照标准，和本文件其它空行一致

2024-01-22 15:15 UTC, panhongtao07 commented on generic/models.py
> +        ))
这个遍历太慢了，ON的外键查询

2024-01-22 15:15 UTC, panhongtao07 commented on generic/backend.py
> +            PermissionBlacklist.get_cancelled_permissions(user_obj)
代码里user就是user，不要加_obj，共用的get_cancelled可以作为方法重用，不要每次调用了外部的了

2024-01-22 15:15 UTC, panhongtao07 commented on generic/backend.py
> +        ))
务必改成一次查询，现在是ON2的，太慢了

2024-01-22 15:15 UTC, panhongtao07 commented on boot/settings.py
> +AUTHENTICATION_BACKENDS = ["generic.backend.BlacklistBackend"]
用多行的吧，每行结尾加逗号，如：
```
AUTHENTICATION_BACKENDS = [
    'generic.backend.BlacklistBackend',
]
```

2024-01-23 02:39 UTC, Deophius commented on Appointment/models.py
> +            ('取消预约', '取消预约')
Resolved in 39fd760

2024-01-23 14:36 UTC, Deophius commented on generic/backend.py
> +            raise ValueError(f'Unknown permission string "{perm}"')
5a7ea03中已解决

2024-01-23 14:36 UTC, Deophius commented on generic/backend.py
> +        type(self)._check_permission_string(perm)
5a7ea03中已解决

2024-01-23 14:36 UTC, Deophius commented on generic/models.py
> +    @staticmethod
5a7ea03中已解决

2024-01-23 14:36 UTC, Deophius commented on generic/models.py
5a7ea03中已解决

2024-01-23 14:36 UTC, Deophius commented on generic/backend.py
> +            PermissionBlacklist.get_cancelled_permissions(user_obj)
5a7ea03中已解决

2024-01-23 14:37 UTC, Deophius commented on boot/settings.py
> +AUTHENTICATION_BACKENDS = ["generic.backend.BlacklistBackend"]
5a7ea03中已解决

2024-01-25 07:03 UTC, panhongtao07 approved these changes
现在这个结构应该比较合理了

2024-01-25 18:31 UTC, merged