补充提交了迁移文件
Yuanpei-Intelligence/YPPF pull request #811
Opened 2024-01-26 04:00 UTC by Morgen-Kornblume

之前实现空盒元气值补偿时因为第一次做忘了提交迁移文件，现在补充提交

2024-01-29 09:01 UTC, panhongtao07 requested changes
建议删除generic目录下这两个文件并重新makemigrations
此外，如果你的历史与yppf:develop不一致，可能影响未来的提交。现在显示你和上游有7个commit差异，适当注意。

2024-01-29 09:03 UTC, panhongtao07 commented on generic/migrations/0003_merge_20240126_1158.py
重新生成一下迁移文件吧

2024-01-30 02:35 UTC, Morgen-Kornblume commented on generic/migrations/0003_merge_20240126_1158.py
已经重新生成了迁移文件，不知道为什么会与上游产生七个差异，但是改动仅限于迁移文件，前几个commit的差异已经在对应的PR中通过了

2024-02-17 11:27 UTC, pkuGenuine approved these changes

2024-02-17 11:27 UTC, merged