地下室使用规范
Yuanpei-Intelligence/YPPF pull request #843
Opened 2024-10-02 12:49 UTC by Deophius

1. 增加了地下室使用规范页面和相应的链接。

在首页上的链接：
<img width="1243" alt="1" src="https://github.com/user-attachments/assets/56947c2c-592f-4e45-ad09-0130dfae3311">

页面内容：
<img width="1263" alt="conduct page 1" src="https://github.com/user-attachments/assets/0104a23d-ec59-4706-8b48-73294219e5b0">

<img width="1268" alt="conduct page 2" src="https://github.com/user-attachments/assets/dc0b8373-7fc5-4199-8bea-4ff8e04a8fbf">

2. 在首页最底下增加了一个可折叠的预约提示：

<img width="1254" alt="help1" src="https://github.com/user-attachments/assets/2aab28dc-7778-4b51-b3b0-51f3a43d82e4">

<img width="1266" alt="help2" src="https://github.com/user-attachments/assets/1e1ade62-cfa4-452f-a81e-1c084ebf2704">

3. 选择房间和时间界面增加了一个温馨提示：

<img width="1265" alt="4" src="https://github.com/user-attachments/assets/940bcdc8-8968-44ef-8831-81d1af12f265">

2024-10-02 12:54 UTC, qingzhenduyu commented on Appointment/urls.py
> +    path('code_of_conduct', views.code_of_conduct, name='code_of_conduct')
code_of_conduct 这个名字，跟“地下室使用规范”感觉一点关系没有，建议换成instructions_underground之类的

2024-10-02 12:58 UTC, qingzhenduyu requested changes
整体没问题的，两个需要修改的小点我写在comment里了

2024-10-02 13:12 UTC, Deophius commented on templates/Appointment/index.html
> +			<section class="section section-doctor" data-toggle="collapse">
直接把这个删了

2024-10-02 13:14 UTC, qingzhenduyu approved these changes

2024-10-02 13:38 UTC, Deophius commented
先别merge，讨论一下这个requirements.txt应该怎么处理

2024-10-03 08:20 UTC, Deophius commented
经过对比实验，发现是typing-extension在requirements.txt中缺失的问题，已经加上了。

2024-10-03 14:41 UTC, pkuGenuine approved these changes

2024-10-04 07:36 UTC, merged